import { ArrowLeft, CheckCircle2, FlaskConical, Paperclip, RefreshCw, XCircle } from 'lucide-react'
import { useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import AppShell from '../../../components/AppShell'
import { Badge, Button, Card, EmptyState, PageTitle } from '../../../components/ui'
import { clinicalApi } from '../../../features/clinical/api/clinical-api'
import { useApiQuery } from '../../../shared/hooks/useApiQuery'

const statusLabel: Record<number, { label: string; tone: 'warning' | 'success' | 'danger' | 'neutral' }> = { 0: { label: 'Đang chờ', tone: 'warning' }, 1: { label: 'Đã có kết quả', tone: 'success' }, 2: { label: 'Đã hủy', tone: 'danger' } }

export default function DoctorServicesPage() {
  const { recordId } = useParams(); const id = Number(recordId); const navigate = useNavigate()
  const [serviceId, setServiceId] = useState(''); const [quantity, setQuantity] = useState('1'); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState<{ type: 'success' | 'error'; text: string } | null>(null)
  const record = useApiQuery(`doctor-services-record-${id}`, () => clinicalApi.record(id))
  const orders = useApiQuery(`doctor-services-orders-${id}`, () => clinicalApi.serviceOrders(id))
  const catalog = useApiQuery('doctor-services-catalog', () => clinicalApi.servicesCatalog())
  const editable = Boolean(record.data && !record.data.isFinalized)
  const add = async () => { if (!serviceId) return; setBusy(true); setNotice(null); try { await clinicalApi.orderService(id, { serviceId: Number(serviceId), quantity: Number(quantity) || 1 }); setNotice({ type: 'success', text: 'Đã thêm chỉ định dịch vụ.' }); setServiceId(''); orders.refresh() } catch (error) { setNotice({ type: 'error', text: error instanceof Error ? error.message : 'Không thể thêm chỉ định.' }) } finally { setBusy(false) } }
  const cancel = async (orderId: number) => { setBusy(true); setNotice(null); try { await clinicalApi.cancelOrder(orderId); setNotice({ type: 'success', text: 'Đã hủy chỉ định.' }); orders.refresh() } catch (error) { setNotice({ type: 'error', text: error instanceof Error ? error.message : 'Không thể hủy chỉ định.' }) } finally { setBusy(false) } }
  return <AppShell><PageTitle eyebrow="Khám bệnh" title="Chỉ định & kết quả" description={`Bệnh án #${id} · chỉ định cận lâm sàng trong lượt khám.`} action={<Button variant="secondary" onClick={() => navigate(`/doctor/exam/${id}`)}><ArrowLeft className="size-4" /> Về bệnh án</Button>} />
    {notice && <p role={notice.type === 'error' ? 'alert' : 'status'} className={`mb-5 flex items-center gap-2 rounded-xl border p-3 text-sm font-semibold ${notice.type === 'error' ? 'border-rose-200 bg-rose-50 text-rose-700' : 'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{notice.type === 'error' ? <XCircle className="size-5" /> : <CheckCircle2 className="size-5" />}{notice.text}</p>}
    {!editable && record.data?.isFinalized && <p className="mb-5 rounded-xl border border-sky-200 bg-sky-50 p-3 text-sm font-semibold text-sky-700">Bệnh án đã chốt, chỉ có thể xem lại chỉ định và kết quả.</p>}
    <Card className="mb-5 p-5"><div className="mb-4 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-sky-50 text-sky-700"><FlaskConical className="size-5" /></span><div><h2 className="font-display text-lg font-bold text-slate-900">Thêm chỉ định</h2><p className="text-sm text-slate-500">Chỉ định sẽ phải có kết quả trước khi hoàn tất lượt khám.</p></div></div><div className="flex flex-col gap-3 lg:flex-row lg:items-end"><label className="min-w-0 flex-1"><span className="field-label">Dịch vụ</span><select disabled={!editable || busy || catalog.loading} value={serviceId} onChange={(event) => setServiceId(event.target.value)} className="input-base"><option value="">Chọn dịch vụ cận lâm sàng</option>{catalog.data?.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.price.toLocaleString('vi-VN')} đ</option>)}</select></label><label className="w-full lg:w-32"><span className="field-label">Số lượng</span><input disabled={!editable || busy} min="1" type="number" value={quantity} onChange={(event) => setQuantity(event.target.value)} className="input-base" /></label><Button disabled={!editable || !serviceId || busy} onClick={() => void add()}>Thêm chỉ định</Button></div>{catalog.error && <p className="mt-3 text-sm text-rose-600">{catalog.error}</p>}</Card>
    {orders.loading ? <Card className="grid min-h-56 place-items-center"><span className="size-9 animate-spin rounded-full border-4 border-teal-100 border-t-teal-700" /></Card> : orders.error ? <Card className="p-8 text-center"><XCircle className="mx-auto size-10 text-rose-500" /><p className="mt-3 text-sm text-slate-500">{orders.error}</p><Button className="mt-5" onClick={orders.refresh}><RefreshCw className="size-4" /> Thử lại</Button></Card> : !orders.data?.length ? <EmptyState icon={<FlaskConical className="size-6" />} title="Chưa có chỉ định" body="Các dịch vụ được chỉ định trong lượt khám sẽ hiển thị ở đây." /> : <Card className="overflow-hidden"><div className="flex flex-col gap-2 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-display text-lg font-bold text-slate-900">Danh sách chỉ định</h2><p className="mt-1 text-sm text-slate-500">Kết quả được cập nhật bởi kỹ thuật viên sau khi thực hiện.</p></div><Button variant="secondary" disabled title="FoMed API hiện chưa có endpoint tải file đính kèm cho chỉ định"><Paperclip className="size-4" /> Đính kèm file</Button></div><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Dịch vụ</th><th>SL</th><th>Đơn giá</th><th>Kết quả</th><th>Trạng thái</th><th /></tr></thead><tbody>{orders.data.map((order) => { const status = statusLabel[order.status] ?? { label: `Mã ${order.status}`, tone: 'neutral' as const }; return <tr key={order.id}><td><strong className="text-slate-800">{order.serviceName}</strong></td><td>{order.quantity}</td><td>{order.unitPriceSnapshot.toLocaleString('vi-VN')} đ</td><td><span className="block max-w-xs whitespace-normal">{order.resultSummary || order.conclusion || 'Chưa có kết quả'}</span>{order.referenceRange && <small className="text-slate-400">Tham chiếu: {order.referenceRange}</small>}</td><td><Badge tone={status.tone}>{status.label}</Badge></td><td>{order.status === 0 && editable && <Button variant="danger" className="h-8 px-3 text-xs" disabled={busy} onClick={() => void cancel(order.id)}>Hủy</Button>}</td></tr> })}</tbody></table></div></Card>}
  </AppShell>
}
