// Source contracts only; real handlers are exercised by isolated browser DEMO.
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
let checks = 0
const check = (ok, label) => { assert.ok(ok, label); checks++; console.log('PASS: ' + label) }
const read = file => fs.readFileSync(path.join(__dirname, '../src/', file), 'utf8')
const patient = read('workspaces/patient/pages/BookingPage.tsx')
const staff = read('workspaces/reception/pages/ReceptionBookingPage.tsx')
const files = read('features/clinical/components/AttachmentPanel.tsx')
const quick = read('workspaces/reception/components/QuickPatientModal.tsx')
for (const [name, source] of [['patient', patient], ['staff', staff], ['files', files]]) {
  check(source.includes("import { notify } from '../../../shared/notifications/notify'"), `${name}: shared adapter`)
  check(!source.includes('<AppToaster') && !source.includes('toast.'), `${name}: no extra toaster`)
  check(source.includes('pending.current') && (source.includes('finally { pending.current = false') || name === 'staff' && source.includes('pending.current = false; setSubmitting(false)')), `${name}: local pending guard released`)
}
check(/await appointmentApi.book\([\s\S]*?notify.success\('Đã gửi yêu cầu đặt lịch.'\)/.test(patient), 'Patient success after API response')
check(patient.includes('Lịch đang chờ lễ tân xác nhận.') && patient.includes('border-sky-200') && !patient.includes('CheckCircle2'), 'Persistent pending status is not duplicate green success')
check(patient.includes('role="alert"') && patient.includes('displayError(reasonValue,'), 'Patient error remains inline and safe')
check(patient.includes('reason.trim().length < 3') && patient.includes('Khung giờ có thể vừa được người khác đặt.'), 'Reason validation and conflict warning retained')
check(/await appointmentApi.staffBook\([\s\S]*?notify.success\('Đã đặt lịch khám.'\)/.test(staff), 'Staff success after response without patient name')
check(!staff.includes('setSuccess') && !staff.includes('{success &&'), 'Staff no duplicate banner')
check(staff.includes('slots.loading || slots.error') && staff.includes('!available.some(item => item.startTime === slot)'), 'Staff blocks stale/failed/unavailable slot')
check((staff.match(/slots.refresh\(\)/g) || []).length === 2, 'Staff reloads availability after success or conflict')
check(staff.includes("notify.success('Đã tạo hồ sơ vãng lai. Bạn có thể tiếp tục chọn lịch khám.')"), 'Quick create feedback has no private identifiers')
check([patient, staff].every(source => source.includes('<fieldset disabled={submitting}')), 'Booking selection locked while response pending')
check(quick.includes('if (pending.current) return') && quick.includes('disabled={saving}') && quick.includes('<fieldset disabled={saving}'), 'Quick create prevents repeats and closing/typing while pending')
check(quick.includes('chưa có tài khoản đăng nhập.') && quick.includes('role="alert"'), 'Guest account explanation and form error retained')
check(files.includes('!canUpload || !file') && files.includes('!attachment.downloadable'), 'Existing upload permission and legacy download restrictions retained')
check(files.includes('file.size <= 0') && files.includes('file.size > 10 * 1024 * 1024') && files.includes('(jpg|jpeg|png|pdf|dicom|dcm)'), 'File size/extension validation retained')
check(/await clinicalApi.uploadAttachment\([\s\S]*?setFile\(null\)[\s\S]*?notify.success\('Đã lưu tệp đính kèm.'\)/.test(files), 'Upload success clears input after response')
check(files.includes('setNotice(displayError(reason,') && files.includes('{notice && <p role="alert"'), 'Upload errors stay beside input')
check(/anchor.click\(\)[\s\S]*?notify.success\('Đã gửi tệp tới trình duyệt để tải xuống.'\)/.test(files), 'Download describes browser handoff, not disk save')
check(files.includes("notify.error(reason, 'Không thể tải tệp xuống.')"), 'Download error uses Sonner and safe message')
check(files.includes('URL.revokeObjectURL(url)') && files.includes('Thử lại danh sách tệp'), 'Blob cleanup and list retry retained')
check(!files.includes('error: false') && !files.includes('bg-emerald-50'), 'Attachment success banner removed')
check(files.includes('Chỉ người có quyền mới được xem và tải tệp.') && files.includes('Tệp cũ chưa chuyển'), 'Access and migration warnings remain persistent')
check(!files.includes('Chọn file') && !files.includes('Tải file'), 'Attachment labels use Vietnamese tệp')
const fixture = fs.readFileSync(path.join(__dirname, 'fixtures/booking-attachments.tsx'), 'utf8')
check(fixture.includes('window.fetch = blocked') && fixture.includes('Object.keys(api)'), 'DEMO blocks external requests')
console.log(`Booking/attachments: ${checks} source contracts passed; not production E2E.`)
