// Only run through the --http --browser fixture: all accounts/data belong to its disposable DB.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright')
const fs = require('node:fs')
const path = require('node:path')
const base = process.env.FOMED_PREVIEW_URL || 'http://127.0.0.1:5184'
const data = JSON.parse(process.env.FOMED_AUDIT_DATA || '{}')
if (!data.recordId || !data.invoiceId) throw new Error('Run from the isolated HTTP audit, not against application data.')
const output = path.resolve(__dirname, '../dist/review-clinic')
const results = []
const check = (ok, label, evidence) => { results.push({ passed: ok, label, evidence }); console.log(`${ok ? 'PASS' : 'FAIL'}: ${label}`) }

async function main() {
  fs.mkdirSync(output, { recursive: true })
  const browser = await chromium.launch({ headless: true })
  try {
    const routes = {
      patient: ['/booking', '/my-appointments', '/my-records', '/my-invoices'],
      receptionist: ['/reception', '/reception/patients', '/reception/booking', '/reception/queue', '/reception/cashier', `/reception/cashier/${data.invoiceId}`],
      doctor: ['/doctor/queue', `/doctor/exam/${data.recordId}`, `/doctor/exam/${data.recordId}/services`, `/doctor/exam/${data.recordId}/prescription`],
      technician: ['/technician/orders', '/technician/results'],
      pharmacist: ['/pharmacy/inventory', '/pharmacy/receipt', '/pharmacy/dispense', `/pharmacy/dispense/${data.prescriptionId}`],
      admin: ['/admin/dashboard', '/admin/reports', '/admin/audit-logs'],
    }
    for (const [role, pages] of process.env.FOMED_JOURNEY_ONLY === '1' ? [] : Object.entries(routes)) {
      const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, timezoneId: 'Asia/Ho_Chi_Minh' })
      const page = await context.newPage()
      const errors = []
      const serverErrors = []
      page.on('pageerror', error => errors.push(error.message))
      page.on('response', response => { if (response.url().includes('/api/') && response.status() >= 500) serverErrors.push({ url: new URL(response.url()).pathname, status: response.status() }) })
      await page.goto(base + '/login')
      await page.getByPlaceholder('Nhập tên đăng nhập', { exact: true }).fill(role)
      await page.getByPlaceholder('Nhập mật khẩu', { exact: true }).fill('Audit-Only!2026')
      await page.getByRole('button', { name: 'Đăng nhập', exact: true }).click()
      await page.waitForURL(url => !url.pathname.includes('/login'))
      check(new URL(page.url()).pathname === pages[0], `${role}: login redirects to correct workspace`, new URL(page.url()).pathname)
      for (const route of pages) {
        for (const width of [1440, 390]) {
          await page.setViewportSize({ width, height: 950 })
          await page.goto(base + route)
          await page.waitForLoadState('networkidle')
          check(new URL(page.url()).pathname === route && await page.locator('h1').count() > 0, `${role} ${route} ${width}: page renders`)
          const overflow = await page.evaluate(() => ({ fits: document.documentElement.scrollWidth <= innerWidth,
            width: document.documentElement.scrollWidth, offenders: [...document.querySelectorAll('main *')].filter(element => element.getBoundingClientRect().right > innerWidth).slice(0, 15).map(element => ({ tag: element.tagName, classes: element.className, right: element.getBoundingClientRect().right })) }))
          check(overflow.fits, `${role} ${route} ${width}: no document overflow`, overflow.fits ? undefined : overflow)
          await page.screenshot({ path: path.join(output, `${role}-${route.replaceAll('/', '_')}-${width}.png`), fullPage: true })
        }
      }
      if (role === 'patient') {
        await page.goto(base + '/my-records')
        await page.getByText('Audit diagnosis', { exact: true }).locator('xpath=../../..').getByRole('button', { name: 'Xem bệnh án', exact: true }).click()
        const dialog = page.getByRole('dialog')
        await dialog.waitFor()
        await dialog.getByText('Audit medicine', { exact: true }).waitFor()
        check(await dialog.locator('table').count() === 3, 'VC-05: patient modal has record, prescription and lab tables')
        await dialog.getByRole('button', { name: 'Tải file đính kèm', exact: true }).click()
        const patientFiles = dialog.getByRole('region', { name: 'File đính kèm', exact: true })
        await patientFiles.getByRole('button', { name: 'Tải file clinical-demo.pdf', exact: true }).waitFor()
        check(await dialog.locator('table').count() === 3 && await patientFiles.getByLabel('Chọn file đính kèm', { exact: true }).count() === 0, 'VC-05 attachment panel preserves three tables and is read-only for patient')
        const patientDownloadPromise = page.waitForEvent('download')
        await patientFiles.getByRole('button', { name: 'Tải file clinical-demo.pdf', exact: true }).click()
        const patientDownload = await patientDownloadPromise
        check(patientDownload.suggestedFilename() === 'clinical-demo.pdf' && await patientDownload.failure() === null, 'Patient downloads authenticated clinical file through modal')
        await page.screenshot({ path: path.join(output, 'patient-record-modal-390.png'), fullPage: true })
        await page.goto(base + '/admin/reports')
        await page.waitForURL('**/forbidden')
        check(true, 'Patient UI cannot enter admin reports')
      }
      if (role === 'admin') {
        await page.goto(base + '/admin/audit-logs')
        await page.waitForLoadState('networkidle')
        check(await page.getByLabel('Loại ghi nhận', { exact: true }).inputValue() === 'Read' && await page.locator('tbody tr').count() === 10, 'VC-24 defaults to medical access logs, 10 rows per page')
        const firstIds = await page.getByRole('button', { name: /^Chi tiết nhật ký #/ }).evaluateAll(buttons => buttons.map(button => button.getAttribute('aria-label')))
        const nextPromise = page.waitForResponse(response => response.url().includes('/api/audit-logs?') && new URL(response.url()).searchParams.get('page') === '2')
        await page.getByRole('button', { name: 'Sau', exact: true }).click()
        await nextPromise
        await page.waitForLoadState('networkidle')
        const secondIds = await page.getByRole('button', { name: /^Chi tiết nhật ký #/ }).evaluateAll(buttons => buttons.map(button => button.getAttribute('aria-label')))
        check(secondIds.length > 0 && secondIds.every(id => !firstIds.includes(id)), 'VC-24 next page loads distinct server audit events')
        let filterRequests = 0
        const auditRequest = request => { if (request.url().includes('/api/audit-logs?')) filterRequests++ }
        page.on('request', auditRequest)
        await page.getByLabel('Mã người thực hiện', { exact: true }).fill(String(data.doctorUserId))
        await page.getByLabel('Loại ghi nhận', { exact: true }).selectOption('Update')
        check(filterRequests === 0, 'Audit filter editing does not issue requests until explicit submit')
        const updatePromise = page.waitForResponse(response => response.url().includes('/api/audit-logs?') && new URL(response.url()).searchParams.get('action') === 'Update')
        await page.getByRole('button', { name: 'Lọc nhật ký', exact: true }).click()
        const updates = await (await updatePromise).json()
        await page.waitForLoadState('networkidle')
        check(updates.items.every(log => log.action === 'Update' && log.userId === data.doctorUserId) && await page.getByText(/^Trang 1 \/ /).count() === 1, 'Audit submit applies actor/action and resets pagination')
        const updateRow = page.locator('tbody tr').filter({ hasText: 'Cập nhật bệnh án' }).first()
        // Other browser roles generated newer write events; do not assume the older UpdateRecord
        // event remains on the first page of a real, paginated audit dataset.
        for (let auditPage = 1; await updateRow.count() === 0 && auditPage < Math.ceil(updates.total / updates.pageSize); auditPage++) {
          const olderPromise = page.waitForResponse(response => response.url().includes('/api/audit-logs?') && new URL(response.url()).searchParams.get('page') === String(auditPage + 1))
          await page.getByRole('button', { name: 'Sau', exact: true }).click()
          await olderPromise
          await page.waitForLoadState('networkidle')
        }
        const detailButton = updateRow.getByRole('button', { name: /^Chi tiết nhật ký #/ })
        await detailButton.click()
        let dialog = page.getByRole('dialog')
        await dialog.waitFor()
        check(await dialog.getByText('Người thực hiện và vai trò được ghi nhận tại thời điểm thao tác.', { exact: true }).count() === 1 && await dialog.getByText('Audit doctor', { exact: true }).count() === 1 && await dialog.getByText('Hướng điều trị', { exact: true }).count() === 1 && await dialog.getByText('Sinh hiệu', { exact: true }).count() === 1, 'Audit detail shows actor snapshot and actual changed field names')
        check(!((await dialog.innerText()).includes('Audit diagnosis')) && !((await dialog.innerText()).includes('PRIVATE_CLINICAL_SENTINEL')), 'Admin audit detail does not expose clinical values or raw snapshots')
        check(await dialog.evaluate(element => { const bounds = element.getBoundingClientRect(); return bounds.left >= 0 && bounds.right <= innerWidth && bounds.height <= innerHeight && element.contains(document.activeElement) }), 'Mobile audit dialog fits viewport and owns keyboard focus')
        await page.screenshot({ path: path.join(output, 'admin-audit-detail-390.png'), fullPage: true })
        await page.keyboard.press('Escape')
        await dialog.waitFor({ state: 'detached' })
        check(await page.getByRole('dialog').count() === 0 && await detailButton.evaluate(button => button === document.activeElement), 'Escape closes audit modal and returns focus to its trigger')
        await page.setViewportSize({ width: 1440, height: 950 })
        await detailButton.click()
        await page.getByRole('dialog').waitFor()
        await page.screenshot({ path: path.join(output, 'admin-audit-detail-1440.png'), fullPage: true })
        await page.getByRole('button', { name: 'Đóng chi tiết nhật ký', exact: true }).click()
        await page.getByLabel('Loại ghi nhận', { exact: true }).selectOption('Read')
        await page.getByLabel('Từ ngày', { exact: true }).fill('2001-01-02')
        await page.getByLabel('Đến ngày', { exact: true }).fill('2001-01-02')
        const datePromise = page.waitForResponse(response => response.url().includes('/api/audit-logs?') && new URL(response.url()).searchParams.has('from'))
        await page.getByRole('button', { name: 'Lọc nhật ký', exact: true }).click()
        const dateResponse = await datePromise
        const dateUrl = new URL(dateResponse.url())
        await page.waitForLoadState('networkidle')
        check(dateUrl.searchParams.get('from') === '2001-01-01T17:00:00.000Z' && dateUrl.searchParams.get('to') === '2001-01-02T17:00:00.000Z' && await page.locator('tbody tr').count() === 1, 'Same-day date filter uses inclusive clinic day instead of excluding end date')
        await page.getByRole('button', { name: `Chi tiết nhật ký #${data.legacyAuditId}`, exact: true }).click()
        dialog = page.getByRole('dialog')
        await dialog.waitFor()
        check(await dialog.getByText('Nhật ký cũ chưa lưu thông tin tại thời điểm thao tác.', { exact: false }).count() === 1 && await dialog.getByText('Không có thông tin trong nhật ký này', { exact: true }).count() === 2, 'Legacy audit modal explains current-account fallback and absent IP/trace')
        await page.getByRole('button', { name: 'Đóng chi tiết nhật ký', exact: true }).click()
        filterRequests = 0
        await page.getByLabel('Mã người thực hiện', { exact: true }).fill('invalid')
        await page.getByRole('button', { name: 'Lọc nhật ký', exact: true }).click()
        await page.getByRole('alert').getByText('Mã người dùng phải là số nguyên dương hợp lệ.', { exact: true }).waitFor()
        check(filterRequests === 0 && await page.locator('tbody tr').count() === 1, 'Invalid audit actor filter preserves existing data and avoids API request')
        const clearPromise = page.waitForResponse(response => response.url().includes('/api/audit-logs?') && !new URL(response.url()).searchParams.has('userId') && new URL(response.url()).searchParams.get('action') === 'Read' && new URL(response.url()).searchParams.get('page') === '1')
        await page.getByRole('button', { name: 'Xóa lọc', exact: true }).click()
        await clearPromise
        await page.waitForLoadState('networkidle')
        check(await page.getByLabel('Loại ghi nhận', { exact: true }).inputValue() === 'Read' && await page.getByLabel('Mã người thực hiện', { exact: true }).inputValue() === '' && await page.locator('tbody tr').count() === 10, 'Clear filters restores default medical access view')
        const auditUrl = '**/api/audit-logs?*'
        await page.route(auditUrl, route => route.abort('failed'))
        await page.reload()
        await page.getByRole('heading', { name: 'Không thể tải dữ liệu', exact: true }).waitFor()
        check(await page.getByRole('button', { name: /^Chi tiết nhật ký #/ }).count() === 0, 'Audit network failure shows retry, not stale audit actions')
        await page.unroute(auditUrl)
        await page.getByRole('button', { name: 'Thử lại', exact: true }).click()
        await page.waitForLoadState('networkidle')
        check(await page.locator('tbody tr').count() === 10, 'Audit retry restores server data')
        page.off('request', auditRequest)
      }
      if (role === 'doctor') {
        await page.goto(base + `/doctor/exam/${data.prescribingRecordId}/services`)
        const doctorFiles = page.getByRole('region', { name: 'File đính kèm', exact: true })
        await doctorFiles.getByLabel('Chọn file đính kèm', { exact: true }).setInputFiles({ name: 'bad.pdf', mimeType: 'application/pdf', buffer: Buffer.from('not a PDF') })
        const failedUploadPromise = page.waitForResponse(response => response.url().includes('/attachments') && response.request().method() === 'POST')
        await doctorFiles.getByRole('button', { name: 'Đính kèm file', exact: true }).click()
        check((await failedUploadPromise).status() === 400, 'Server rejects a spoofed PDF uploaded through UI')
        await doctorFiles.getByRole('alert').waitFor()
        check(await doctorFiles.getByLabel('Chọn file đính kèm', { exact: true }).evaluate(input => input.files[0]?.name === 'bad.pdf'), 'Failed upload retains selected file and shows error')
        await doctorFiles.getByLabel('Chọn file đính kèm', { exact: true }).setInputFiles({ name: 'browser-doctor.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\n%%EOF') })
        const doctorUploadPromise = page.waitForResponse(response => response.url().includes('/attachments') && response.request().method() === 'POST')
        await doctorFiles.getByRole('button', { name: 'Đính kèm file', exact: true }).click()
        check((await doctorUploadPromise).status() === 201, 'Doctor uploads attachment through real multipart API')
        await doctorFiles.getByText('Đã lưu file đính kèm.', { exact: true }).waitFor()
        await doctorFiles.getByRole('button', { name: 'Tải file browser-doctor.pdf', exact: true }).waitFor()
        await page.reload()
        await doctorFiles.getByRole('button', { name: 'Tải file browser-doctor.pdf', exact: true }).waitFor()
        check(true, 'Uploaded clinical attachment persists after page reload')
        await page.screenshot({ path: path.join(output, 'doctor-attachments-390.png'), fullPage: true })
        await page.goto(base + `/doctor/exam/${data.recordId}/prescription`)
        await page.waitForLoadState('networkidle')
        if (!data.focusDispensing) check(await page.getByText('Audit Penicillin', { exact: false }).count() > 0, 'VC-15: allergy warning survives direct URL/reload')
        await page.goto(base + `/doctor/exam/${data.draftId}/prescription`)
        await page.getByText('Đơn thuốc đã được cấp phát, không thể chỉnh sửa.', { exact: false }).waitFor()
        check(await page.getByRole('button', { name: 'Cập nhật đơn thuốc', exact: true }).isDisabled(), 'Partially dispensed draft: update button disabled')
        check(await page.getByRole('heading', { name: 'Tìm và thêm thuốc', exact: true }).count() === 0, 'Partially dispensed draft: medicine picker is hidden')
        await page.goto(base + `/doctor/exam/${data.prescribingRecordId}/prescription`)
        await page.waitForLoadState('networkidle')
        check(await page.getByText('Audit Penicillin', { exact: true }).count() > 0, 'Editable deep link loads server allergy')
        check(await page.getByRole('button', { name: 'Thêm thuốc Catalog medicine 01', exact: true }).isDisabled(), 'Zero-stock medicine cannot be selected')
        await page.getByRole('button', { name: 'Trang sau', exact: true }).click()
        await page.getByRole('button', { name: 'Thêm thuốc ZZZ Search beyond first page', exact: true }).waitFor()
        check(true, 'Medicine picker paginates beyond the first 20 results')
        await page.getByPlaceholder('Nhập tên thuốc...', { exact: true }).fill('ZZZ')
        const searchPromise = page.waitForResponse(response => response.url().includes('/api/clinical/medicines/search?') && new URL(response.url()).searchParams.get('keyword') === 'ZZZ')
        await page.getByRole('button', { name: 'Tìm thuốc', exact: true }).click()
        await searchPromise
        await page.getByText(/^1 thuốc · Trang\s*1$/).waitFor()
        await page.waitForLoadState('networkidle')
        check(await page.getByText(/^1 thuốc · Trang\s*1$/).count() === 1, 'Keyword search resets pagination and total')
        await page.getByRole('button', { name: 'Thêm thuốc ZZZ Search beyond first page', exact: true }).click()
        check(await page.getByRole('button', { name: 'Thêm thuốc ZZZ Search beyond first page', exact: true }).isDisabled(), 'Same medicine cannot be added twice')
        await page.getByLabel('Liều dùng', { exact: true }).fill('Audit dosage')
        await page.getByRole('button', { name: 'Lưu đơn thuốc', exact: true }).click()
        await page.getByText('Bệnh nhân có tiền sử dị ứng. Vui lòng kiểm tra và xác nhận trước khi lưu.', { exact: true }).waitFor()
        check(true, 'Allergy acknowledgment required in UI')
        await page.getByRole('checkbox', { name: 'Đã kiểm tra dị ứng thuốc' }).check()
        await page.getByLabel('Số lượng', { exact: true }).fill('11')
        await page.getByRole('button', { name: 'Lưu đơn thuốc', exact: true }).click()
        await page.getByText('Số lượng kê vượt tồn khả dụng. Vui lòng kiểm tra các dòng thuốc.', { exact: true }).waitFor()
        check(await page.getByText('Vượt tồn khả dụng', { exact: true }).count() > 0, 'Quantity above unexpired stock is blocked in UI')
        await page.getByLabel('Số lượng', { exact: true }).fill('2')
        const savePromise = page.waitForResponse(response => response.url().endsWith(`/api/clinical/records/${data.prescribingRecordId}/prescription`) && response.request().method() === 'POST')
        await page.getByRole('button', { name: 'Lưu đơn thuốc', exact: true }).click()
        check((await savePromise).status() === 201, 'Medicine selected from server search creates prescription via real API')
        await page.getByRole('button', { name: 'Cập nhật đơn thuốc', exact: true }).waitFor()
        await page.reload()
        await page.waitForLoadState('networkidle')
        check(await page.getByText('Audit Penicillin', { exact: true }).count() > 0 && await page.getByRole('heading', { name: 'ZZZ Search beyond first page', exact: true }).count() > 0, 'Reload preserves allergy and saved medicine outside first page')
        check(await page.getByRole('checkbox', { name: 'Đã kiểm tra dị ứng thuốc' }).isChecked() === false, 'Reload requires a fresh allergy acknowledgment for edits')
        await page.getByRole('checkbox', { name: 'Đã kiểm tra dị ứng thuốc' }).check()
        await page.getByLabel('Số lượng', { exact: true }).fill('3')
        // A second role changes stock after the doctor's screen has loaded (real API, disposable DB only).
        const pharmacyLogin = await page.request.post(base + '/api/auth/login', { data: { username: 'pharmacist', password: 'Audit-Only!2026' } })
        const pharmacySession = await pharmacyLogin.json()
        const headers = { Authorization: `Bearer ${(pharmacySession.dataResponse || pharmacySession).accessToken}` }
        const inventoryResponse = await page.request.get(base + `/api/pharmacy/inventory?medicineId=${data.browserMedicineId}`, { headers })
        const inventoryBody = await inventoryResponse.json()
        const stockBatch = (inventoryBody.dataResponse || inventoryBody).find(batch => batch.lotNumber === 'BROWSER-VALID')
        if (!stockBatch) throw new Error('Disposable browser batch missing')
        const adjustment = await page.request.post(base + '/api/pharmacy/inventory/adjustments', { headers, data: { batchId: stockBatch.batchId, quantity: -9, reason: 'Isolated stock race test' } })
        if (adjustment.status() !== 200) throw new Error('Cannot set up isolated stock race')
        await page.getByLabel('Ghi chú đơn thuốc', { exact: true }).fill('Keep unsaved note on stock conflict')
        const conflictPromise = page.waitForResponse(response => response.url().endsWith(`/api/clinical/records/${data.prescribingRecordId}/prescription`) && response.request().method() === 'PUT')
        await page.getByRole('button', { name: 'Cập nhật đơn thuốc', exact: true }).click()
        check((await conflictPromise).status() === 409, 'API rechecks stock changed after screen load')
        await page.getByText('Thuốc ZZZ Search beyond first page chỉ còn 1', { exact: false }).waitFor()
        await page.waitForLoadState('networkidle')
        check(await page.getByLabel('Số lượng', { exact: true }).inputValue() === '3' && await page.getByLabel('Ghi chú đơn thuốc', { exact: true }).inputValue() === 'Keep unsaved note on stock conflict', 'Stock conflict keeps unsaved prescription input')
        await page.getByText('Vượt tồn khả dụng', { exact: true }).waitFor()
        check(true, 'Stock conflict refreshes availability in selected medicine')
        const restock = await page.request.post(base + '/api/pharmacy/inventory/adjustments', { headers, data: { batchId: stockBatch.batchId, quantity: 9, reason: 'Restore isolated browser stock' } })
        if (restock.status() !== 200) throw new Error('Cannot restore isolated browser stock')
        await page.getByPlaceholder('Nhập tên thuốc...', { exact: true }).fill('ZZZ')
        const refreshSearchPromise = page.waitForResponse(response => response.url().includes('/api/clinical/medicines/search?') && new URL(response.url()).searchParams.get('keyword') === 'ZZZ')
        await page.getByRole('button', { name: 'Tìm thuốc', exact: true }).click()
        await refreshSearchPromise
        await page.waitForLoadState('networkidle')
        const updatePromise = page.waitForResponse(response => response.url().endsWith(`/api/clinical/records/${data.prescribingRecordId}/prescription`) && response.request().method() === 'PUT')
        await page.getByRole('button', { name: 'Cập nhật đơn thuốc', exact: true }).click()
        check((await updatePromise).status() === 200, 'Editing stocked draft prescription succeeds through UI')
        await page.waitForLoadState('networkidle')
        const contextUrl = `**/api/clinical/records/${data.prescribingRecordId}/prescribing-context*`
        await page.route(contextUrl, route => route.abort('failed'))
        await page.goto(base + `/doctor/exam/${data.prescribingRecordId}/prescription`)
        await page.getByText('Chưa tải được thông tin dị ứng.', { exact: true }).first().waitFor()
        check(await page.getByRole('button', { name: 'Cập nhật đơn thuốc', exact: true }).isDisabled(), 'Missing allergy context blocks saving rather than assuming no allergy')
        await page.unroute(contextUrl)
        await page.getByRole('button', { name: 'Tải lại hồ sơ kê đơn', exact: true }).click()
        await page.getByText('Audit Penicillin', { exact: true }).first().waitFor()
        await page.waitForLoadState('networkidle')
        check(await page.getByRole('button', { name: 'Cập nhật đơn thuốc', exact: true }).isEnabled(), 'Retry restores prescribing context and enables editing')
        await page.screenshot({ path: path.join(output, 'doctor-prescribing-search-390.png'), fullPage: true })
        check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Editable medicine picker has no mobile document overflow')
        await page.goto(base + `/doctor/exam/${data.recordId}/services`)
        await page.waitForLoadState('networkidle')
        check(await page.getByRole('button', { name: 'Thêm chỉ định', exact: true }).isDisabled(), 'Finalized record: adding orders disabled in UI')
        check(await page.getByRole('button', { name: 'Hủy chỉ định', exact: true }).count() === 0, 'Completed/canceled orders: no cancel action in UI')
        check(await page.getByLabel('Chọn file đính kèm', { exact: true }).count() === 0, 'Finalized clinical attachments are read-only for doctor')
      }
      if (role === 'technician') {
        await page.goto(base + '/technician/results')
        await page.waitForLoadState('networkidle')
        check(await page.locator('tbody tr').count() === 10, 'Technician history loads ten real server results in a fresh browser session')
        const nextHistoryPromise = page.waitForResponse(response => response.url().includes('/api/clinical/lab-results?') && new URL(response.url()).searchParams.get('page') === '2')
        await page.getByRole('button', { name: 'Sau', exact: true }).click()
        await nextHistoryPromise
        await page.waitForFunction(() => document.querySelectorAll('tbody tr').length === 3)
        check(await page.locator('tbody tr').count() === 3, 'Technician history loads remaining results on page two')
        const previousHistoryPromise = page.waitForResponse(response => response.url().includes('/api/clinical/lab-results?') && new URL(response.url()).searchParams.get('page') === '1')
        await page.getByRole('button', { name: 'Trước', exact: true }).click()
        await previousHistoryPromise
        await page.locator('tbody tr').filter({ hasText: 'HGB 13.2' }).waitFor()
        await page.locator('tbody tr').filter({ hasText: 'HGB 13.2' }).getByRole('button', { name: 'File kết quả', exact: true }).click()
        const technicianFiles = page.getByRole('region', { name: 'File đính kèm', exact: true })
        await technicianFiles.getByRole('button', { name: 'Tải file lab-demo.png', exact: true }).waitFor()
        check(await technicianFiles.getByRole('button', { name: 'Tải file clinical-demo.pdf', exact: true }).count() === 0, 'Technician panel shows only selected result files, not the full clinical record')
        await technicianFiles.getByLabel('Chọn file đính kèm', { exact: true }).setInputFiles({ name: 'kết-quả.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\n%%EOF') })
        const technicianUploadPromise = page.waitForResponse(response => response.url().includes(`/attachments?orderId=${data.orderId}`) && response.request().method() === 'POST')
        await technicianFiles.getByRole('button', { name: 'Đính kèm file', exact: true }).click()
        check((await technicianUploadPromise).status() === 201, 'Technician appends file to own completed result through UI')
        await technicianFiles.getByRole('button', { name: 'Tải file kết-quả.pdf', exact: true }).waitFor()
        const labDownloadPromise = page.waitForEvent('download')
        await technicianFiles.getByRole('button', { name: 'Tải file kết-quả.pdf', exact: true }).click()
        const labDownload = await labDownloadPromise
        check(labDownload.suggestedFilename() === 'kết-quả.pdf' && await labDownload.failure() === null, 'Technician downloads result file with original Vietnamese filename')
        await page.screenshot({ path: path.join(output, 'technician-result-files-390.png'), fullPage: true })
        await page.goto(base + '/technician/orders')
        await page.waitForLoadState('networkidle')
        await page.locator('tbody tr').filter({ hasText: `#${data.prescribingRecordId}` }).getByRole('button', { name: 'Nhập kết quả', exact: true }).click()
        await page.getByPlaceholder('Nhập kết quả đo/xét nghiệm...', { exact: true }).fill('Browser result')
        const resultSavePromise = page.waitForResponse(response => response.url().endsWith(`/api/clinical/lab-orders/${data.pendingUiOrderId}/result`) && response.request().method() === 'POST')
        await page.getByRole('button', { name: 'Lưu kết quả', exact: true }).click()
        check((await resultSavePromise).status() === 201, 'Technician submits result through real API')
        await page.goto(base + '/technician/results')
        await page.getByText('Browser result', { exact: true }).waitFor()
        await page.reload()
        await page.getByText('Browser result', { exact: true }).waitFor()
        check(true, 'New result appears in server history and survives reload')
        await page.locator('tbody tr').filter({ hasText: 'Browser result' }).getByRole('button', { name: 'File kết quả', exact: true }).click()
        await technicianFiles.getByLabel('Chọn file đính kèm', { exact: true }).setInputFiles({ name: 'new-result.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\n%%EOF') })
        const newResultFilePromise = page.waitForResponse(response => response.url().includes(`/attachments?orderId=${data.pendingUiOrderId}`) && response.request().method() === 'POST')
        await technicianFiles.getByRole('button', { name: 'Đính kèm file', exact: true }).click()
        check((await newResultFilePromise).status() === 201, 'New result attachment works when order ID differs from result ID')
        await technicianFiles.getByRole('button', { name: 'Tải file new-result.pdf', exact: true }).waitFor()
        const newResultDownloadPromise = page.waitForEvent('download')
        await technicianFiles.getByRole('button', { name: 'Tải file new-result.pdf', exact: true }).click()
        const newResultDownload = await newResultDownloadPromise
        check(newResultDownload.suggestedFilename() === 'new-result.pdf' && await newResultDownload.failure() === null, 'Result attachment lookup/download respects distinct owner and order IDs')
        await page.getByPlaceholder('Tìm dịch vụ, tên bệnh nhân hoặc mã BN...', { exact: true }).fill('does-not-exist')
        await page.getByRole('button', { name: 'Lọc kết quả', exact: true }).click()
        await page.getByText('Chưa có kết quả phù hợp', { exact: true }).waitFor()
        check(await page.locator('tbody tr').count() === 0, 'Technician history search displays an explicit empty state')
        const historyUrl = '**/api/clinical/lab-results?*'
        await page.route(historyUrl, route => route.abort('failed'))
        await page.reload()
        await page.getByRole('button', { name: 'Thử lại', exact: true }).waitFor()
        check(await page.locator('tbody tr').count() === 0, 'History network failure hides stale result actions')
        await page.unroute(historyUrl)
        await page.getByRole('button', { name: 'Thử lại', exact: true }).click()
        await page.getByText('Browser result', { exact: true }).waitFor()
        check(true, 'Technician history retry restores server results')
      }
      if (role === 'pharmacist') {
        await page.goto(base + '/pharmacy/dispense')
        await page.waitForLoadState('networkidle')
        check(await page.locator('tbody tr').count() === 10, 'Pharmacist selects from real pending prescriptions, ten per page')
        const firstPrescriptionIds = await page.locator('tbody tr td:first-child strong').allTextContents()
        const nextPrescriptionPromise = page.waitForResponse(response => response.url().includes('/api/pharmacy/prescriptions?') && new URL(response.url()).searchParams.get('page') === '2')
        await page.getByRole('button', { name: 'Sau', exact: true }).click()
        await nextPrescriptionPromise
        await page.waitForFunction(() => document.querySelectorAll('tbody tr').length > 0 && document.querySelectorAll('tbody tr').length < 10)
        const nextPrescriptionIds = await page.locator('tbody tr td:first-child strong').allTextContents()
        check(nextPrescriptionIds.length > 0 && nextPrescriptionIds.every(id => !firstPrescriptionIds.includes(id)), 'Pharmacy list pagination loads distinct prescriptions')
        await page.getByPlaceholder('Tìm tên bệnh nhân, mã BN hoặc mã đơn...', { exact: true }).fill(String(data.uiRxId))
        const filteredPrescriptionPromise = page.waitForResponse(response => response.url().includes('/api/pharmacy/prescriptions?') && new URL(response.url()).searchParams.get('keyword') === String(data.uiRxId))
        await page.getByRole('button', { name: 'Lọc đơn', exact: true }).click()
        await filteredPrescriptionPromise
        await page.waitForFunction(() => document.querySelectorAll('tbody tr').length === 1)
        check(await page.locator('tbody tr').count() === 1, 'Pharmacy keyword filter resets page and finds exact prescription')
        await page.getByRole('link', { name: 'Kiểm tra & phát thuốc', exact: true }).click()
        await page.waitForURL(`**/pharmacy/dispense/${data.uiRxId}`)
        await page.getByRole('columnheader', { name: 'Lô đề xuất FEFO', exact: true }).waitFor()
        check(await page.getByRole('columnheader', { name: 'Lô đề xuất FEFO', exact: true }).count() === 1 && await page.getByRole('columnheader', { name: 'Tồn lô', exact: true }).count() === 1, 'Selected prescription shows proposed batches and stock before confirmation')
        await page.screenshot({ path: path.join(output, 'pharmacy-preview-390.png'), fullPage: true })
        await page.goto(base + `/pharmacy/dispense/${data.prescriptionId}`)
        await page.getByText('Đã phát đủ', { exact: true }).first().waitFor()
        check(await page.getByRole('button', { name: 'Xác nhận phát thuốc', exact: true }).isDisabled(), 'Fully dispensed: confirm disabled')
        await page.goto(base + `/pharmacy/dispense/${data.draftRxId}`)
        await page.getByText('Bệnh án chưa chốt hoặc lượt khám chưa hoàn tất, chưa thể phát thuốc.', { exact: true }).waitFor()
        check(await page.getByRole('button', { name: 'Xác nhận phát thuốc', exact: true }).isDisabled(), 'Draft prescription: confirm disabled with reason')
        await page.getByPlaceholder('Ví dụ: 332').fill('2147483647')
        check(await page.getByRole('button', { name: 'Xác nhận phát thuốc', exact: true }).count() === 0, 'Changed search ID discards old prescription actions')
        await page.getByRole('button', { name: 'Tra cứu đơn', exact: true }).click()
        await page.getByText('Không tìm thấy đơn thuốc.', { exact: true }).waitFor()
        check(await page.getByRole('button', { name: 'Xác nhận phát thuốc', exact: true }).count() === 0, 'Unknown prescription has no dispense action')
        await page.goto(base + `/pharmacy/dispense/${data.uiRxId}`)
        const confirm = page.getByRole('button', { name: 'Xác nhận phát thuốc', exact: true })
        await page.getByText('Sẵn sàng cấp phát', { exact: true }).waitFor()
        check(await confirm.isEnabled(), 'Eligible finalized prescription can be confirmed')
        const responsePromise = page.waitForResponse(response => response.url().endsWith(`/api/pharmacy/prescriptions/${data.uiRxId}/dispense`) && response.request().method() === 'POST')
        await confirm.click()
        const response = await responsePromise
        check(response.status() === 200, 'Browser confirmation calls real dispense API successfully')
        await page.getByText('Đã phát thuốc thành công theo nguyên tắc FEFO.', { exact: true }).waitFor()
        await page.getByText('Đã phát đủ', { exact: true }).first().waitFor()
        check(await page.getByRole('button', { name: 'Xác nhận phát thuốc', exact: true }).isDisabled(), 'After successful confirmation: duplicate submit is disabled')
        await page.screenshot({ path: path.join(output, 'pharmacy-confirmed-390.png'), fullPage: true })
      }
      check(errors.length === 0, `${role}: no uncaught JS errors`, errors)
      check(serverErrors.length === 0, `${role}: no API 5xx when loading pages`, serverErrors)
      await context.close()
    }
    if (process.env.FOMED_JOURNEY_DATA) await require('./clinic-workflow.e2e.cjs').run(browser, JSON.parse(process.env.FOMED_JOURNEY_DATA))
  } catch (error) {
    check(false, 'Browser automation exception', error.message)
    throw error
  } finally {
    await browser.close()
    fs.writeFileSync(path.join(output, 'ui-audit.json'), JSON.stringify(results, null, 2))
  }
  if (results.some(result => !result.passed)) process.exitCode = 1
}
main().catch(error => { console.error(error); process.exitCode = 1 })
