// Source contracts only; actual handlers are exercised in the isolated browser DEMO.
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
let checks = 0
const check = (ok, label) => { assert.ok(ok, label); checks++; console.log('PASS: ' + label) }
const source = fs.readFileSync(path.join(__dirname, '../src/workspaces/pharmacy/pages/PharmacyInventoryPage.tsx'), 'utf8')
check(source.includes("import { notify } from '../../../shared/notifications/notify'"), 'Shared notification adapter')
check(!source.includes("type: 'success'") && !source.includes('CheckCircle2'), 'No duplicate success banner')
check(!source.includes('<AppToaster') && !source.includes('toast.'), 'No extra toaster')
check(/await pharmacyApi.receiveStock\([\s\S]*?setModal\(null\)[\s\S]*?notify.success\('Đã nhập lô thuốc vào kho.'\)/.test(source), 'Receive success closes dialog only after response')
check(/await pharmacyApi.adjustStock\([\s\S]*?setModal\(null\)[\s\S]*?notify.success\('Đã điều chỉnh tồn kho và lưu nhật ký thay đổi.'\)/.test(source), 'Adjustment success follows response and closes dialog')
check((source.match(/mutationPending.current = true/g) || []).length === 2 && (source.match(/mutationPending.current = false/g) || []).length === 2, 'Both writes have local pending guards')
check(source.includes("modal !== 'receive'") && source.includes("modal !== 'adjust'"), 'Only active form can submit')
check(source.includes('!Number.isInteger(quantity)') && source.includes('Math.abs(quantity) > 1000000'), 'Integer and adjustment range match backend DTO')
check(source.includes('quantity <= 0 || quantity > 2147483647') && source.includes('!receive.lotNumber.trim()'), 'Quick receipt validates quantity and whitespace lot')
check(source.includes('quantity === 0') && source.includes('!adjust.reason.trim()'), 'Zero delta and missing reason rejected')
check(source.includes('maxLength={255}') && source.includes('maxLength={50}'), 'Reason and lot length limits match backend DTO')
check(source.includes('Số dương tăng tồn kho, số âm giảm tồn kho.'), 'Persistent effect warning retained')
check(source.includes('role="dialog" aria-modal="true" aria-labelledby="inventory-dialog-title"'), 'Modal has named dialog semantics')
check((source.match(/\{notice && <p role="alert"/g) || []).length === 2 && source.indexOf('{notice && <p role="alert"') > source.indexOf('role="dialog"'), 'Mutation errors render inside each form dialog')
check((source.match(/displayError\(error,/g) || []).length === 2, 'Both internal errors use safe Vietnamese copy')
check(source.includes('<fieldset disabled={busy}') && source.includes('if (!mutationPending.current) { setModal(null)'), 'Pending form and close locked')
check(source.includes('event.currentTarget === event.target) close()'), 'Backdrop uses guarded close')
check(source.includes('transactions.refresh()') && source.includes('inventory.refresh()'), 'Inventory and selected journal refreshed after adjustment')
check(source.includes('setReceive({ medicineId: \'\', lotNumber: \'\', expiryDate: \'\', quantity: \'1\' })'), 'Successful quick receipt clears fields')
check(source.includes('medicines.error && <p role="alert"') && source.includes('Thử tải lại danh sách thuốc'), 'Catalog failure offers inline retry')
check(source.includes('disabled={busy || medicines.loading || !!medicines.error}'), 'Failed catalog blocks quick receipt')
const messages = [...source.matchAll(/notify.success\('([^']+)'\)/g)].map(match => match[1])
check(messages.length === 2 && messages.every(message => /[À-ỹ]/u.test(message) && !/medicineName|reason|quantity|#|SqlClient/.test(message)), 'Accented operation messages contain no private values')
console.log(`Inventory notifications: ${checks} source contracts passed. Not production E2E; see browser DEMO.`)
