// Source contracts only; actual handlers are checked with the isolated browser fixture.
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
let checks = 0
const check = (ok, label) => { assert.ok(ok, label); checks++; console.log('PASS: ' + label) }
const read = file => fs.readFileSync(path.join(__dirname, '..', file), 'utf8')
const source = read('src/workspaces/technician/pages/TechnicianOrdersPage.tsx')
check(source.includes("import { notify } from '../../../shared/notifications/notify'"), 'Shared notification adapter')
check(!source.includes("type: 'success'") && !source.includes('CheckCircle2'), 'No duplicate inline success banner')
check(source.includes('role="alert"') && source.includes('displayError(error,'), 'Contextual safe errors retained')
check(!source.includes('<AppToaster') && !source.includes('toast.'), 'No second toaster or adapter bypass')
check(/await clinicalApi.saveLabResult\([\s\S]*?notify.success\('Đã lưu kết quả và cập nhật trạng thái chỉ định.'\)/.test(source), 'Success follows resolved save')
check(source.includes('if (!value.resultSummary.trim())'), 'Required summary validation retained')
check(source.includes('resultSummary: value.resultSummary.trim()') && source.includes('conclusion: value.conclusion.trim() || undefined') && source.includes('referenceRange: value.referenceRange.trim() || undefined'), 'Optional fields and trimming retained')
check(source.includes('mutationPending.current = true') && source.includes('mutationPending.current = false'), 'Pending guard is released')
check(source.includes('selected !== order.id') && source.includes('!rows.some(item => item.id === order.id)'), 'Only selected loaded order can submit')
check(/await clinicalApi.saveLabResult\([\s\S]*?setSelected\(null\)[\s\S]*?orders.refresh\(\)/.test(source), 'Saved editor closes and pending list refreshes')
check(!/catch \(error\) \{[\s\S]*?setDrafts/.test(source), 'Save error does not reset draft fields')
const messages = [...source.matchAll(/notify.success\('([^']+)'\)/g)].map(match => match[1])
check(messages.length === 1 && messages.every(message => /[À-ỹ]/u.test(message) && !/serviceName|patient|resultSummary|#/.test(message)), 'Generic accented success without clinical data')
check(source.includes('disabled={busy}') && source.includes("busy ? 'Đang lưu...' : 'Lưu kết quả'"), 'Pending editor is disabled')
const fixture = read('tests/fixtures/technician-notifications.tsx')
check(fixture.includes('window.fetch = unavailable') && fixture.includes('Object.keys(clinicalApi)'), 'Fixture blocks external requests')
check(fixture.includes('<StrictMode>') && fixture.includes('<AppToaster />'), 'Fixture uses real toaster under StrictMode')
console.log(`Technician notifications: ${checks} source contracts passed. Not production E2E; see browser DEMO.`)
