import { useState, type ReactNode } from 'react'
import { useLocation } from 'react-router-dom'
import {
  Activity, AlertTriangle, ArrowDownRight, ArrowRight, ArrowUpRight, CalendarDays,
  Check, CheckCircle2, ChevronRight, CircleDollarSign, Clock3, Download,
  FileText, FlaskConical, HeartPulse, MoreHorizontal, PackageOpen, PencilLine, Pill,
  Plus, Printer, RefreshCw, ShieldAlert, Stethoscope, Trash2, TrendingUp,
  UserRound, UsersRound, WalletCards,
} from 'lucide-react'
import AppShell from '../components/AppShell'
import { Badge, Button, Card, Field, PageTitle, SearchBox, SelectBox } from '../components/ui'
import { screenMeta } from '../data/navigation'
import type { Appointment, AppointmentStatus } from '../types'

const appointmentsSeed: Appointment[] = [
  { id: 1, time: '08:30', queue: '09', patient: 'Hoàng Minh Quân', code: 'BN000089', phone: '0908 214 650', doctor: 'BS. Lê Hoàng Nam', specialty: 'Nội tổng quát', status: 'Hoàn tất', checkedIn: '08:16' },
  { id: 2, time: '09:00', queue: '12', patient: 'Trần Thị Bích', code: 'BN000125', phone: '0935 682 140', doctor: 'TS.BS Nguyễn Văn An', specialty: 'Tim mạch', status: 'Đã check-in', checkedIn: '08:48' },
  { id: 3, time: '09:30', patient: 'Lê Văn Cường', code: 'BN000340', phone: '0982 451 036', doctor: 'TS.BS Nguyễn Văn An', specialty: 'Tim mạch', status: 'Chờ xác nhận' },
  { id: 4, time: '10:00', queue: '14', patient: 'Phạm Ngọc Diệp', code: 'BN000218', phone: '0914 387 220', doctor: 'BS.CKI Trần Hải Yến', specialty: 'Da liễu', status: 'Đang khám', checkedIn: '09:42' },
  { id: 5, time: '10:30', patient: 'Nguyễn Thị Hà', code: 'BN000411', phone: '0902 177 391', doctor: 'BS. Lê Hoàng Nam', specialty: 'Nội tổng quát', status: 'Không đến' },
]

const toneForStatus = (status: AppointmentStatus) => status === 'Hoàn tất' || status === 'Đã check-in' ? 'success' : status === 'Chờ xác nhận' ? 'warning' : status === 'Không đến' ? 'danger' : 'info'
const money = (value: number) => new Intl.NumberFormat('vi-VN').format(value) + 'đ'

function Header({ action }: { action?: ReactNode }) {
  const path = useLocation().pathname
  const normalized = path.match(/^\/reception\/cashier/) ? '/reception/cashier/871' : path.match(/^\/doctor\/exam\/[^/]+\/services/) ? '/doctor/exam/451/services' : path.match(/^\/doctor\/exam\/[^/]+\/prescription/) ? '/doctor/exam/451/prescription' : path.match(/^\/doctor\/exam/) ? '/doctor/exam/451' : path.match(/^\/pharmacy\/dispense/) ? '/pharmacy/dispense/451' : path
  const meta = screenMeta[normalized] ?? { eyebrow: 'FoMed workspace', title: 'Không gian làm việc', description: 'Quản lý vận hành phòng khám.' }
  return <PageTitle {...meta} action={action} />
}

function StatCard({ label, value, detail, icon: Icon, tone = 'teal', trend }: { label: string; value: string; detail: string; icon: typeof Activity; tone?: 'teal' | 'blue' | 'amber' | 'rose'; trend?: 'up' | 'down' }) {
  const colors = { teal: 'bg-teal-50 text-teal-700', blue: 'bg-sky-50 text-sky-700', amber: 'bg-amber-50 text-amber-700', rose: 'bg-rose-50 text-rose-700' }
  return <Card className="p-5"><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-2 font-display text-[28px] font-bold tracking-tight text-slate-900">{value}</p></div><span className={`grid size-11 place-items-center rounded-xl ${colors[tone]}`}><Icon className="size-5" /></span></div><p className={`mt-3 flex items-center gap-1 text-xs ${trend ? trend === 'up' ? 'text-emerald-600' : 'text-rose-600' : 'text-slate-400'}`}>{trend === 'up' && <ArrowUpRight className="size-3.5" />}{trend === 'down' && <ArrowDownRight className="size-3.5" />}{detail}</p></Card>
}

function ReceptionPage() {
  const [items, setItems] = useState(appointmentsSeed)
  const [query, setQuery] = useState('')
  const filtered = items.filter((x) => `${x.patient} ${x.code} ${x.phone}`.toLowerCase().includes(query.toLowerCase()))
  const checkIn = (id: number) => setItems((all) => all.map((x) => x.id === id ? { ...x, queue: '15', checkedIn: '10:02', status: 'Đã check-in' } : x))

  return <><Header action={<Button><Plus className="size-4" /> Đặt lịch tại quầy</Button>} />
    <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
      <StatCard label="Tổng lịch hẹn" value="42" detail="Hôm nay, 01/10" icon={CalendarDays} />
      <StatCard label="Chờ đến" value="15" detail="3 lịch trong 30 phút" icon={Clock3} tone="amber" />
      <StatCard label="Đã check-in" value="8" detail="Đang trong hàng chờ" icon={CheckCircle2} tone="blue" />
      <StatCard label="Đã khám xong" value="17" detail="Tăng 12% so với hôm qua" icon={Stethoscope} trend="up" />
      <StatCard label="Không đến" value="2" detail="Cần liên hệ lại" icon={UserRound} tone="rose" />
    </div>
    <Card className="overflow-hidden">
      <div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row"><SearchBox value={query} onChange={setQuery} placeholder="Tìm theo tên, mã BN hoặc số điện thoại..." /><SelectBox className="sm:w-44">Tất cả chuyên khoa</SelectBox><SelectBox className="sm:w-44">Tất cả bác sĩ</SelectBox><Button variant="secondary"><RefreshCw className="size-4" /> Làm mới</Button></div>
      <div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Giờ khám</th><th>STT</th><th>Bệnh nhân</th><th>Bác sĩ phụ trách</th><th>Trạng thái</th><th className="text-right">Thao tác</th></tr></thead><tbody>{filtered.map((row) => <tr key={row.id}><td><span className="font-bold text-slate-900">{row.time}</span>{row.checkedIn && <span className="block text-xs text-slate-400">Đến {row.checkedIn}</span>}</td><td>{row.queue ? <span className="grid size-9 place-items-center rounded-lg bg-teal-50 font-display font-bold text-teal-700">{row.queue}</span> : <span className="text-slate-300">—</span>}</td><td><strong className="block text-sm text-slate-800">{row.patient}</strong><span className="text-xs text-slate-400">{row.code} · {row.phone}</span></td><td><span className="block text-sm text-slate-700">{row.doctor}</span><span className="text-xs text-slate-400">{row.specialty}</span></td><td><Badge tone={toneForStatus(row.status)}>{row.status}</Badge></td><td><div className="flex justify-end gap-2">{row.status === 'Chờ xác nhận' && <Button className="h-9" onClick={() => checkIn(row.id)}><Check className="size-4" /> Check-in</Button>}<button className="grid size-9 place-items-center rounded-lg border border-slate-200 text-slate-400 hover:text-slate-700"><MoreHorizontal className="size-4" /></button></div></td></tr>)}</tbody></table></div>
      <div className="flex items-center justify-between border-t border-slate-100 px-5 py-4 text-xs text-slate-500"><span>Hiển thị 1–5 trong 42 lịch hẹn</span><div className="flex gap-1"><button className="page-button">‹</button><button className="page-button active">1</button><button className="page-button">2</button><button className="page-button">3</button><button className="page-button">›</button></div></div>
    </Card>
  </>
}

function AdminDashboard() {
  return <><Header action={<div className="flex gap-2"><SelectBox>01/10/2026</SelectBox><Button variant="secondary"><Download className="size-4" /> Xuất báo cáo</Button></div>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Lượt khám hôm nay" value="128" detail="8,2% so với hôm qua" icon={UsersRound} trend="up" /><StatCard label="Doanh thu hôm nay" value="42,8 tr" detail="12,5% so với hôm qua" icon={CircleDollarSign} tone="blue" trend="up" /><StatCard label="Đang chờ khám" value="18" detail="Chờ trung bình 16 phút" icon={Clock3} tone="amber" /><StatCard label="Công suất phòng khám" value="86%" detail="4 bác sĩ đang làm việc" icon={Activity} tone="rose" /></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.55fr_1fr]">
      <Card className="p-5 sm:p-6"><div className="mb-7 flex items-center justify-between"><div><h2 className="font-display text-lg font-bold text-slate-900">Doanh thu 7 ngày gần nhất</h2><p className="mt-1 text-xs text-slate-400">Đơn vị: triệu đồng</p></div><Badge tone="success"><TrendingUp className="mr-1 size-3" /> +14,2%</Badge></div><div className="flex h-64 items-end gap-3 sm:gap-5">{[48, 66, 54, 82, 72, 93, 78].map((height, i) => <div key={i} className="flex h-full flex-1 flex-col justify-end gap-2"><div className="group relative flex-1 rounded-t-lg bg-slate-100"><div style={{ height: `${height}%` }} className={`absolute inset-x-0 bottom-0 rounded-t-lg transition-all ${i === 5 ? 'bg-teal-700' : 'bg-teal-200 group-hover:bg-teal-300'}`}><span className="absolute -top-6 left-1/2 hidden -translate-x-1/2 text-[10px] font-bold text-slate-500 sm:block">{Math.round(height / 1.7)}tr</span></div></div><span className="text-center text-[11px] text-slate-400">T{i + 2}</span></div>)}</div></Card>
      <Card className="p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><h2 className="font-display text-lg font-bold text-slate-900">Phân bổ lượt khám</h2><button className="text-xs font-semibold text-teal-700">Xem chi tiết</button></div><div className="grid place-items-center py-2"><div className="relative grid size-40 place-items-center rounded-full" style={{ background: 'conic-gradient(#0f766e 0 42%, #38bdf8 42% 69%, #fbbf24 69% 86%, #e2e8f0 86%)' }}><div className="grid size-28 place-items-center rounded-full bg-white text-center"><span><strong className="block font-display text-3xl text-slate-900">128</strong><small className="text-slate-400">lượt khám</small></span></div></div></div><div className="mt-5 grid grid-cols-2 gap-3 text-xs">{[['Tim mạch','42%','bg-teal-700'],['Nội tổng quát','27%','bg-sky-400'],['Da liễu','17%','bg-amber-400'],['Khác','14%','bg-slate-200']].map(([name, val, color]) => <div key={name} className="flex items-center justify-between"><span className="flex items-center gap-2 text-slate-500"><i className={`size-2 rounded-full ${color}`} />{name}</span><b>{val}</b></div>)}</div></Card>
    </div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.3fr_1fr]"><Card className="overflow-hidden"><div className="flex items-center justify-between p-5"><h2 className="font-display text-lg font-bold">Hoạt động gần đây</h2><button className="text-xs font-semibold text-teal-700">Xem tất cả</button></div>{[['BN000125 đã hoàn tất khám Tim mạch','2 phút trước','bg-emerald-100 text-emerald-700'],['Hóa đơn HD2026-000871 đã thanh toán','8 phút trước','bg-sky-100 text-sky-700'],['BS. Lê Hoàng Nam cập nhật lịch nghỉ','21 phút trước','bg-amber-100 text-amber-700'],['Lô thuốc PAR-0926 sắp hết hạn','45 phút trước','bg-rose-100 text-rose-700']].map(([title,time,color], i) => <div key={title} className="flex items-center gap-3 border-t border-slate-100 px-5 py-3.5"><span className={`grid size-9 place-items-center rounded-xl ${color}`}>{i === 0 ? <Stethoscope className="size-4" /> : i === 1 ? <WalletCards className="size-4" /> : i === 2 ? <CalendarDays className="size-4" /> : <Pill className="size-4" />}</span><span className="flex-1 text-sm font-medium text-slate-700">{title}</span><span className="text-xs text-slate-400">{time}</span></div>)}</Card><Card className="p-5"><h2 className="font-display text-lg font-bold">Tình trạng hệ thống</h2><div className="mt-5 space-y-5">{[['Kết nối hệ thống','99,98%','bg-emerald-500'],['Lịch hẹn hôm nay','42 / 56 lượt','bg-teal-600'],['Kho thuốc cần chú ý','6 mặt hàng','bg-amber-500']].map(([label,value,color]) => <div key={label}><div className="mb-2 flex justify-between text-sm"><span className="text-slate-500">{label}</span><b className="text-slate-700">{value}</b></div><div className="h-1.5 rounded-full bg-slate-100"><div className={`h-full rounded-full ${color}`} style={{ width: label.startsWith('Kết nối') ? '99%' : label.startsWith('Lịch') ? '75%' : '32%' }} /></div></div>)}</div></Card></div>
  </>
}

function BookingPage() {
  const [step, setStep] = useState(1)
  const specialties = [['Tim mạch','Tim và hệ tuần hoàn',HeartPulse],['Nội tổng quát','Khám và tư vấn tổng quát',Stethoscope],['Da liễu','Da, tóc và móng',Activity],['Xét nghiệm','Kiểm tra cận lâm sàng',FlaskConical]] as const
  return <><Header />
    <div className="mb-7 flex max-w-3xl items-center">{['Chuyên khoa','Bác sĩ','Thời gian','Xác nhận'].map((label, i) => <div key={label} className="flex flex-1 items-center last:flex-none"><button onClick={() => setStep(i + 1)} className="flex items-center gap-2"><span className={`grid size-8 place-items-center rounded-full text-xs font-bold ${step >= i + 1 ? 'bg-teal-700 text-white' : 'bg-slate-200 text-slate-500'}`}>{step > i + 1 ? <Check className="size-4" /> : i + 1}</span><span className={`hidden text-xs font-semibold sm:block ${step >= i + 1 ? 'text-teal-800' : 'text-slate-400'}`}>{label}</span></button>{i < 3 && <div className={`mx-3 h-px flex-1 ${step > i + 1 ? 'bg-teal-600' : 'bg-slate-200'}`} />}</div>)}</div>
    {step === 1 && <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{specialties.map(([name, desc, Icon], i) => <button key={name} onClick={() => setStep(2)} className="group rounded-2xl border border-slate-200 bg-white p-6 text-left shadow-sm transition hover:-translate-y-1 hover:border-teal-300 hover:shadow-lg hover:shadow-teal-900/5"><span className={`grid size-12 place-items-center rounded-2xl ${i === 0 ? 'bg-rose-50 text-rose-600' : i === 1 ? 'bg-teal-50 text-teal-700' : i === 2 ? 'bg-amber-50 text-amber-700' : 'bg-sky-50 text-sky-700'}`}><Icon className="size-6" /></span><h3 className="mt-5 font-display text-lg font-bold text-slate-900">{name}</h3><p className="mt-1 text-sm text-slate-500">{desc}</p><span className="mt-5 flex items-center gap-1 text-xs font-bold text-teal-700 opacity-0 transition group-hover:opacity-100">Chọn chuyên khoa <ArrowRight className="size-3" /></span></button>)}</div>}
    {step === 2 && <div className="grid gap-4 lg:grid-cols-3">{[['TS.BS Nguyễn Văn An','18 năm kinh nghiệm','300.000đ'],['BS.CKI Trần Hải Yến','12 năm kinh nghiệm','250.000đ'],['BS. Phạm Minh Đức','9 năm kinh nghiệm','220.000đ']].map(([name, exp, fee], i) => <Card key={name} className="p-5"><div className="flex items-center gap-4"><span className={`grid size-14 place-items-center rounded-2xl text-lg font-bold ${i === 0 ? 'bg-teal-100 text-teal-800' : 'bg-slate-100 text-slate-600'}`}>{name.split(' ').at(-1)?.[0]}</span><div><h3 className="font-display font-bold text-slate-900">{name}</h3><p className="text-xs text-slate-500">Chuyên khoa Tim mạch · {exp}</p></div></div><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><strong className="text-sm text-teal-700">{fee}</strong><Button onClick={() => setStep(3)}>Chọn bác sĩ</Button></div></Card>)}</div>}
    {step === 3 && <Card className="grid overflow-hidden lg:grid-cols-[.75fr_1.25fr]"><div className="border-b border-slate-100 p-6 lg:border-b-0 lg:border-r"><h3 className="font-display font-bold">Tháng 10, 2026</h3><div className="mt-5 grid grid-cols-7 gap-1 text-center text-xs"><>{['T2','T3','T4','T5','T6','T7','CN'].map(d => <span className="py-2 text-slate-400" key={d}>{d}</span>)}</>{Array.from({length: 31}, (_, i) => <button key={i} className={`aspect-square rounded-lg ${i + 1 === 1 ? 'bg-teal-700 font-bold text-white' : i < 3 ? 'text-slate-300' : 'text-slate-600 hover:bg-teal-50'}`}>{i + 1}</button>)}</div></div><div className="p-6"><p className="text-sm font-bold text-slate-800">Khung giờ còn trống · Thứ Năm, 01/10</p><div className="mt-5 grid grid-cols-3 gap-3 sm:grid-cols-4">{['08:00','08:30','09:00','09:30','10:30','14:00','14:30','15:00','15:30','16:00'].map((time, i) => <button onClick={() => setStep(4)} disabled={i === 2} key={time} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-semibold text-slate-600 hover:border-teal-600 hover:text-teal-700 disabled:bg-slate-50 disabled:text-slate-300">{time}</button>)}</div></div></Card>}
    {step === 4 && <Card className="mx-auto max-w-2xl overflow-hidden"><div className="bg-teal-700 p-6 text-white"><p className="text-xs font-bold uppercase tracking-wider text-teal-100">Xác nhận lịch khám</p><h3 className="mt-2 font-display text-2xl font-bold">Tim mạch · 08:30</h3><p className="mt-1 text-sm text-teal-50/70">Thứ Năm, ngày 01 tháng 10 năm 2026</p></div><div className="space-y-4 p-6"><div className="grid gap-4 rounded-xl bg-slate-50 p-4 sm:grid-cols-2"><p className="text-xs text-slate-400">Bác sĩ<strong className="mt-1 block text-sm text-slate-800">TS.BS Nguyễn Văn An</strong></p><p className="text-xs text-slate-400">Phí khám dự kiến<strong className="mt-1 block text-sm text-slate-800">300.000đ</strong></p></div><Field label="Lý do khám" type="textarea" placeholder="Mô tả ngắn triệu chứng của bạn..." /><Button className="w-full"><CheckCircle2 className="size-4" /> Xác nhận đặt lịch</Button></div></Card>}
  </>
}

function QueuePage({ doctor = false }: { doctor?: boolean }) {
  const queue = appointmentsSeed.filter(x => x.status === 'Đã check-in' || x.status === 'Đang khám')
  return <><Header action={<Button><RefreshCw className="size-4" /> Cập nhật hàng chờ</Button>} /><div className="grid gap-5 xl:grid-cols-[1fr_360px]"><Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="font-display text-lg font-bold">Phòng 204 · Tim mạch</h2><p className="text-xs text-slate-400">TS.BS Nguyễn Văn An</p></div><Badge tone="success"><span className="mr-1.5 size-1.5 animate-pulse rounded-full bg-emerald-500" /> Đang hoạt động</Badge></div><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>STT</th><th>Bệnh nhân</th><th>Giờ hẹn</th><th>Thời gian chờ</th><th>Trạng thái</th><th /></tr></thead><tbody>{queue.map((row, i) => <tr key={row.id} className={i === 0 ? 'bg-teal-50/40' : ''}><td><span className="font-display text-xl font-bold text-teal-700">{row.queue}</span></td><td><strong className="block">{row.patient}</strong><span className="text-xs text-slate-400">{row.code}</span></td><td>{row.time}</td><td>{i ? '22 phút' : 'Đang khám'}</td><td><Badge tone={i ? 'warning' : 'info'}>{i ? 'Đang chờ' : 'Trong phòng'}</Badge></td><td>{doctor ? <Button className="h-9">Bắt đầu khám <ChevronRight className="size-4" /></Button> : <button className="text-xs font-bold text-teal-700">Gọi lại</button>}</td></tr>)}</tbody></table></div></Card><div className="space-y-5"><Card className="overflow-hidden bg-teal-700 p-6 text-white"><p className="text-xs font-bold uppercase tracking-wider text-teal-100">Đang khám</p><p className="mt-4 font-display text-6xl font-bold">12</p><p className="mt-3 text-lg font-semibold">Trần Thị Bích</p><p className="text-sm text-teal-100/70">Bắt đầu lúc 09:04</p></Card><Card className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Tiếp theo</p><div className="mt-4 flex items-center gap-4"><span className="grid size-12 place-items-center rounded-xl bg-amber-50 font-display text-xl font-bold text-amber-700">13</span><div><strong className="block">Lê Văn Cường</strong><span className="text-xs text-slate-400">Hẹn lúc 09:30</span></div></div>{doctor ? <Button className="mt-5 w-full">Gọi bệnh nhân tiếp theo</Button> : <Button variant="secondary" className="mt-5 w-full">Chuyển cuối hàng</Button>}</Card></div></div></>
}

function PatientsPage() {
  const patients = [['BN000125','Trần Thị Bích','Nữ · 34 tuổi','0935 682 140','Penicillin'],['BN000340','Lê Văn Cường','Nam · 47 tuổi','0982 451 036','Không'],['BN000218','Phạm Ngọc Diệp','Nữ · 28 tuổi','0914 387 220','Hải sản'],['BN000411','Nguyễn Thị Hà','Nữ · 51 tuổi','0902 177 391','Không']]
  return <><Header action={<Button><Plus className="size-4" /> Tạo hồ sơ</Button>} /><Card className="overflow-hidden"><div className="flex gap-3 border-b border-slate-100 p-4"><SearchBox placeholder="Tìm theo tên, mã bệnh nhân hoặc SĐT..." /><SelectBox>Trạng thái: Tất cả</SelectBox></div><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Mã BN</th><th>Họ tên</th><th>Thông tin</th><th>Số điện thoại</th><th>Dị ứng</th><th /></tr></thead><tbody>{patients.map(p => <tr key={p[0]}><td className="font-bold text-teal-700">{p[0]}</td><td className="font-bold text-slate-800">{p[1]}</td><td>{p[2]}</td><td>{p[3]}</td><td>{p[4] === 'Không' ? <span className="text-slate-400">Chưa ghi nhận</span> : <Badge tone="danger"><AlertTriangle className="mr-1 size-3" />{p[4]}</Badge>}</td><td><Button variant="ghost">Xem hồ sơ <ChevronRight className="size-4" /></Button></td></tr>)}</tbody></table></div></Card></>
}

function StaffBookingPage() {
  return <><Header /><div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><Card className="p-6"><h2 className="font-display text-lg font-bold">Thông tin lịch hẹn</h2><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Bệnh nhân *" placeholder="Tìm theo số điện thoại..." /><Field label="Nguồn đặt lịch *" value="Khách đến trực tiếp" /><Field label="Chuyên khoa *" value="Tim mạch" /><Field label="Bác sĩ *" value="TS.BS Nguyễn Văn An" /><Field label="Ngày khám *" type="date" value="2026-10-01" /><Field label="Giờ khám *" value="10:30" /><Field label="Lý do khám" type="textarea" placeholder="Nhập triệu chứng..." className="sm:col-span-2" /></div><div className="mt-6 flex justify-end gap-3"><Button variant="secondary">Hủy</Button><Button><CalendarDays className="size-4" /> Xác nhận đặt lịch</Button></div></Card><Card className="self-start p-6"><h2 className="font-display text-lg font-bold">Bệnh nhân đã chọn</h2><div className="mt-5 flex items-center gap-3 rounded-xl bg-teal-50 p-4"><span className="grid size-11 place-items-center rounded-full bg-teal-700 font-bold text-white">LC</span><div><strong className="text-sm">Lê Văn Cường</strong><p className="text-xs text-slate-500">BN000340 · 0982 451 036</p></div></div><div className="mt-5 space-y-3 text-sm"><p className="flex justify-between"><span className="text-slate-400">Ngày sinh</span><b>12/08/1979</b></p><p className="flex justify-between"><span className="text-slate-400">Giới tính</span><b>Nam</b></p><p className="flex justify-between"><span className="text-slate-400">BHYT</span><b>DN4010123456789</b></p></div><button className="mt-5 w-full rounded-xl border border-dashed border-teal-300 p-3 text-sm font-bold text-teal-700"><Plus className="mr-1 inline size-4" /> Tạo nhanh bệnh nhân mới</button></Card></div></>
}

function ExamPage() {
  return <><Header action={<Badge tone="danger"><AlertTriangle className="mr-1 size-3" /> DỊ ỨNG: Penicillin</Badge>} />
    <div className="grid gap-6 xl:grid-cols-[340px_1fr]"><div className="space-y-5"><Card className="p-5"><h2 className="font-display font-bold">Sinh hiệu</h2><div className="mt-4 grid grid-cols-2 gap-3">{[['Mạch','82 l/p'],['Huyết áp','120/80'],['Nhiệt độ','37.0 °C'],['Cân nặng','52 kg']].map(([label,value]) => <div key={label} className="rounded-xl bg-slate-50 p-3"><span className="block text-[11px] text-slate-400">{label}</span><strong className="mt-1 block text-sm">{value}</strong></div>)}</div><Button variant="secondary" className="mt-4 w-full"><PencilLine className="size-4" /> Cập nhật sinh hiệu</Button></Card><Card className="p-5"><h2 className="font-display font-bold">Lịch sử khám gần đây</h2><div className="mt-4 space-y-4">{[['12/03/2026','Viêm họng cấp','J02.9'],['05/01/2026','Khám tổng quát','—']].map(([date,title,code]) => <button key={date} className="block w-full border-l-2 border-teal-200 pl-3 text-left"><span className="text-[11px] text-slate-400">{date}</span><strong className="mt-0.5 block text-sm">{title}</strong><span className="text-xs text-teal-700">{code}</span></button>)}</div></Card></div><Card className="p-6"><div className="flex items-center justify-between"><h2 className="font-display text-lg font-bold">Nội dung bệnh án</h2><Badge tone="warning">Bản nháp</Badge></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Triệu chứng *" type="textarea" value="Đau ngực trái, khó thở khi gắng sức khoảng 2 tuần." className="sm:col-span-2" /><Field label="Chẩn đoán *" value="Đau thắt ngực ổn định" /><Field label="Mã ICD-10" value="I20.8" /><Field label="Hướng điều trị" type="textarea" value="Điều chỉnh lối sống, theo dõi huyết áp. Tái khám sau 7 ngày." className="sm:col-span-2" /><Field label="Ghi chú nội bộ" type="textarea" placeholder="Chỉ hiển thị cho nhân viên y tế..." className="sm:col-span-2" /></div><div className="mt-6 flex flex-wrap justify-between gap-3 border-t border-slate-100 pt-5"><Button variant="secondary"><FileText className="size-4" /> Lưu nháp</Button><div className="flex flex-wrap gap-2"><Button variant="secondary"><FlaskConical className="size-4" /> Chỉ định CLS</Button><Button variant="secondary"><Pill className="size-4" /> Kê đơn</Button><Button><CheckCircle2 className="size-4" /> Hoàn tất khám</Button></div></div></Card></div>
  </>
}

function ClinicalServicesPage({ technician = false }: { technician?: boolean }) {
  const rows = [['XN-MAU','Xét nghiệm máu tổng quát','08:54','Đang thực hiện'],['ECG-01','Điện tâm đồ 12 chuyển đạo','09:02','Chờ thực hiện'],['SA-TIM','Siêu âm tim Doppler','09:05','Hoàn tất']]
  return <><Header action={!technician && <Button><Plus className="size-4" /> Thêm chỉ định</Button>} /><Card className="overflow-hidden"><div className="flex gap-3 border-b border-slate-100 p-4"><SearchBox placeholder="Tìm theo tên bệnh nhân hoặc dịch vụ..." /><SelectBox>Tất cả trạng thái</SelectBox></div><div className="overflow-x-auto"><table className="data-table"><thead><tr>{technician && <th>Bệnh nhân</th>}<th>Mã DV</th><th>Dịch vụ</th><th>Thời gian</th><th>Trạng thái</th><th /></tr></thead><tbody>{rows.map((r, i) => <tr key={r[0]}>{technician && <td><strong>Trần Thị Bích</strong><span className="block text-xs text-slate-400">BN000125</span></td>}<td className="font-bold text-teal-700">{r[0]}</td><td><strong className="text-sm">{r[1]}</strong><span className="block text-xs text-slate-400">Chỉ định bởi TS.BS Nguyễn Văn An</span></td><td>{r[2]}</td><td><Badge tone={r[3] === 'Hoàn tất' ? 'success' : r[3] === 'Đang thực hiện' ? 'info' : 'warning'}>{r[3]}</Badge></td><td>{technician ? <Button className="h-9" variant={i === 2 ? 'secondary' : 'primary'}>{i === 2 ? 'Xem kết quả' : 'Nhập kết quả'}</Button> : <button className="text-sm font-bold text-teal-700">{i === 2 ? 'Xem kết quả' : 'Hủy'}</button>}</td></tr>)}</tbody></table></div></Card></>
}

function PrescriptionPage({ dispensing = false }: { dispensing?: boolean }) {
  const meds = [['Paracetamol 500mg','20 viên','Sáng 1 · chiều 1','Uống sau ăn','Lô PAR-0926'],['Aspirin 81mg','30 viên','Sáng 1','Uống sau ăn sáng','Lô ASP-1126'],['Atorvastatin 20mg','14 viên','Tối 1','Uống trước khi ngủ','Lô ATO-1026']]
  const total = 187000
  return <><Header action={dispensing ? <Badge tone="warning">Chờ phát thuốc</Badge> : <Button><Plus className="size-4" /> Thêm thuốc</Button>} /><div className="grid gap-6 xl:grid-cols-[1fr_330px]"><Card className="overflow-hidden"><div className="border-b border-slate-100 p-5"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-full bg-teal-100 font-bold text-teal-800">TB</span><div><h2 className="font-display font-bold">Trần Thị Bích · BN000125</h2><p className="text-xs text-slate-400">Đơn #DT2026-00451 · TS.BS Nguyễn Văn An</p></div></div></div><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Thuốc</th><th>Số lượng</th><th>Liều dùng</th><th>Hướng dẫn</th>{dispensing && <th>Lô xuất theo hạn dùng</th>}<th /></tr></thead><tbody>{meds.map((m) => <tr key={m[0]}><td><strong>{m[0]}</strong><span className="block text-xs text-slate-400">Tồn khả dụng: 248</span></td><td>{m[1]}</td><td>{m[2]}</td><td>{m[3]}</td>{dispensing && <td><Badge tone="info">{m[4]}</Badge></td>}<td>{!dispensing && <button className="text-slate-400 hover:text-rose-600"><Trash2 className="size-4" /></button>}</td></tr>)}</tbody></table></div>{!dispensing && <div className="border-t border-slate-100 p-5"><Field label="Lời dặn của bác sĩ" type="textarea" value="Uống thuốc đúng liều, tái khám sau 7 ngày hoặc sớm hơn nếu đau ngực tăng." /></div>}</Card><div className="space-y-5"><Card className="border-rose-200 bg-rose-50 p-5"><div className="flex gap-3"><ShieldAlert className="size-5 shrink-0 text-rose-600" /><div><strong className="text-sm text-rose-800">Cảnh báo dị ứng</strong><p className="mt-1 text-xs leading-5 text-rose-700">Bệnh nhân dị ứng Penicillin. Không có hoạt chất xung đột trong đơn hiện tại.</p></div></div></Card><Card className="p-5"><h3 className="font-display font-bold">Tóm tắt đơn thuốc</h3><div className="mt-4 space-y-3 text-sm"><p className="flex justify-between"><span className="text-slate-400">Số loại thuốc</span><b>3</b></p><p className="flex justify-between"><span className="text-slate-400">Tổng số lượng</span><b>64 viên</b></p><p className="flex justify-between border-t border-slate-100 pt-3"><span className="text-slate-500">Thành tiền</span><b className="text-lg text-teal-700">{money(total)}</b></p></div><Button className="mt-5 w-full">{dispensing ? <><PackageOpen className="size-4" /> Xác nhận phát thuốc</> : <><Check className="size-4" /> Lưu đơn thuốc</>}</Button><Button variant="secondary" className="mt-2 w-full"><Printer className="size-4" /> In đơn</Button></Card></div></div></>
}

function CashierPage() {
  return <><Header action={<Badge tone="warning">Thanh toán một phần</Badge>} /><div className="grid gap-6 xl:grid-cols-[1fr_370px]"><Card className="overflow-hidden"><div className="grid gap-4 border-b border-slate-100 p-6 sm:grid-cols-3"><div><span className="text-xs text-slate-400">Bệnh nhân</span><strong className="mt-1 block">Trần Thị Bích</strong><span className="text-xs text-teal-700">BN000125</span></div><div><span className="text-xs text-slate-400">Hóa đơn</span><strong className="mt-1 block">HD2026-000871</strong><span className="text-xs text-slate-400">01/10/2026</span></div><div><span className="text-xs text-slate-400">Bác sĩ</span><strong className="mt-1 block">TS.BS Nguyễn Văn An</strong><span className="text-xs text-slate-400">Tim mạch</span></div></div><table className="data-table"><thead><tr><th>Nội dung</th><th>SL</th><th>Đơn giá</th><th className="text-right">Thành tiền</th></tr></thead><tbody>{[['Phí khám chuyên khoa','1','300.000đ','300.000đ'],['Xét nghiệm máu tổng quát','1','250.000đ','250.000đ'],['Thuốc theo đơn','1','187.000đ','187.000đ']].map(r => <tr key={r[0]}>{r.map((c,i)=><td key={c} className={i === 3 ? 'text-right font-bold' : ''}>{c}</td>)}</tr>)}</tbody></table><div className="space-y-2 border-t border-slate-100 bg-slate-50 p-5 text-sm"><p className="flex justify-end gap-20"><span className="text-slate-500">Tạm tính</span><b className="w-28 text-right">737.000đ</b></p><p className="flex justify-end gap-20"><span className="text-slate-500">BHYT hỗ trợ</span><b className="w-28 text-right text-emerald-600">−177.000đ</b></p><p className="flex justify-end gap-20 pt-2 text-base"><span className="font-bold">Tổng thanh toán</span><b className="w-28 text-right text-teal-700">560.000đ</b></p></div></Card><Card className="self-start p-6"><h2 className="font-display text-lg font-bold">Ghi nhận thanh toán</h2><div className="mt-5 rounded-xl bg-amber-50 p-4"><span className="text-xs text-amber-700">Số tiền còn lại</span><strong className="mt-1 block font-display text-3xl text-amber-800">360.000đ</strong><span className="text-xs text-amber-600">Đã thanh toán 200.000đ</span></div><div className="mt-5 space-y-4"><Field label="Số tiền thu" value="360.000" /><Field label="Phương thức" value="Tiền mặt" /><Field label="Ghi chú" placeholder="Ghi chú giao dịch..." /></div><Button className="mt-5 w-full"><WalletCards className="size-4" /> Xác nhận thu tiền</Button><Button variant="secondary" className="mt-2 w-full"><Printer className="size-4" /> In hóa đơn</Button></Card></div></>
}

function InventoryPage() {
  const inventory = [['MED001','Paracetamol 500mg','Viên','1.248','PAR-0926','30/09/2027','Ổn định'],['MED014','Aspirin 81mg','Viên','620','ASP-1126','30/11/2027','Ổn định'],['MED021','Atorvastatin 20mg','Viên','48','ATO-1026','31/10/2026','Sắp hết hạn'],['MED032','Amoxicillin 500mg','Viên','18','AMX-0926','15/10/2026','Sắp hết']]
  return <><Header action={<div className="flex gap-2"><Button variant="secondary"><RefreshCw className="size-4" /> Điều chỉnh kho</Button><Button><Plus className="size-4" /> Nhập thuốc</Button></div>} /><div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Tổng mặt hàng" value="184" detail="42 nhóm hoạt chất" icon={Pill} /><StatCard label="Tổng tồn kho" value="24.680" detail="Đơn vị tồn khả dụng" icon={PackageOpen} tone="blue" /><StatCard label="Sắp hết hàng" value="6" detail="Dưới ngưỡng tồn tối thiểu" icon={AlertTriangle} tone="amber" /><StatCard label="Sắp hết hạn" value="4" detail="Trong vòng 60 ngày" icon={Clock3} tone="rose" /></div><Card className="overflow-hidden"><div className="flex gap-3 border-b border-slate-100 p-4"><SearchBox placeholder="Tìm tên hoặc mã thuốc..." /><SelectBox>Tất cả trạng thái</SelectBox></div><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Mã thuốc</th><th>Tên thuốc</th><th>Tồn kho</th><th>Lô ưu tiên</th><th>Hạn dùng</th><th>Trạng thái</th><th /></tr></thead><tbody>{inventory.map(r => <tr key={r[0]}><td className="font-bold text-teal-700">{r[0]}</td><td><strong>{r[1]}</strong><span className="block text-xs text-slate-400">Đơn vị: {r[2]}</span></td><td className="font-bold">{r[3]}</td><td>{r[4]}</td><td>{r[5]}</td><td><Badge tone={r[6] === 'Ổn định' ? 'success' : r[6] === 'Sắp hết hạn' ? 'danger' : 'warning'}>{r[6]}</Badge></td><td><button className="text-sm font-bold text-teal-700">Chi tiết lô</button></td></tr>)}</tbody></table></div></Card></>
}

const managementData = {
  '/admin/doctors': { button: 'Thêm bác sĩ', icon: Stethoscope, columns: ['Bác sĩ','Chuyên khoa','Phòng khám','Phí khám','Trạng thái'], rows: [['TS.BS Nguyễn Văn An','Tim mạch','P.204','300.000đ','Hoạt động'],['BS.CKI Trần Hải Yến','Da liễu','P.305','250.000đ','Hoạt động'],['BS. Lê Hoàng Nam','Nội tổng quát','P.202','220.000đ','Tạm nghỉ']] },
  '/admin/schedules': { button: 'Thêm lịch làm việc', icon: CalendarDays, columns: ['Bác sĩ','Ngày làm việc','Ca khám','Nghỉ giữa ca','Slot'], rows: [['TS.BS Nguyễn Văn An','Thứ 2 – Thứ 6','08:00 – 17:00','11:30 – 13:30','30 phút'],['BS.CKI Trần Hải Yến','Thứ 3, 5, 7','13:00 – 17:00','—','20 phút'],['BS. Lê Hoàng Nam','Thứ 2 – Thứ 7','07:30 – 11:30','—','30 phút']] },
  '/admin/services': { button: 'Thêm dịch vụ', icon: Activity, columns: ['Mã DV','Tên dịch vụ','Chuyên khoa','Đơn giá','Thời lượng'], rows: [['DV001','Khám chuyên khoa Tim mạch','Tim mạch','300.000đ','30 phút'],['DV014','Xét nghiệm máu tổng quát','—','250.000đ','15 phút'],['DV021','Siêu âm tim Doppler','Tim mạch','450.000đ','30 phút']] },
  '/admin/users': { button: 'Thêm người dùng', icon: UserRound, columns: ['Người dùng','Email','Vai trò','Đăng nhập cuối','Trạng thái'], rows: [['Nguyễn Văn An','bacsi.an@fomed.vn','Bác sĩ','01/10 · 09:02','Hoạt động'],['Minh Anh','letan.anh@fomed.vn','Lễ tân','01/10 · 09:14','Hoạt động'],['Trần Quốc Bảo','duoc.bao@fomed.vn','Dược sĩ','30/09 · 16:45','Khóa']] },
}

function ManagementPage({ path }: { path: keyof typeof managementData }) {
  const data = managementData[path]
  const Icon = data.icon
  return <><Header action={<Button><Plus className="size-4" /> {data.button}</Button>} /><Card className="overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row"><SearchBox placeholder="Tìm kiếm trong danh sách..." /><SelectBox>Tất cả trạng thái</SelectBox><Button variant="secondary"><Download className="size-4" /> Xuất dữ liệu</Button></div><div className="overflow-x-auto"><table className="data-table"><thead><tr>{data.columns.map(c => <th key={c}>{c}</th>)}<th /></tr></thead><tbody>{data.rows.map((r, rowIndex) => <tr key={r[0]}>{r.map((cell, i) => <td key={cell}>{i === 0 ? <span className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-teal-50 text-teal-700"><Icon className="size-4" /></span><strong className="text-slate-800">{cell}</strong></span> : i === r.length - 1 && (cell === 'Hoạt động' || cell === 'Tạm nghỉ' || cell === 'Khóa') ? <Badge tone={cell === 'Hoạt động' ? 'success' : cell === 'Tạm nghỉ' ? 'warning' : 'danger'}>{cell}</Badge> : cell}</td>)}<td><button aria-label={`Sửa dòng ${rowIndex + 1}`} className="grid size-9 place-items-center rounded-lg text-slate-400 hover:bg-slate-100 hover:text-teal-700"><PencilLine className="size-4" /></button></td></tr>)}</tbody></table></div></Card></>
}

function AuditPage() {
  const logs = [['09:42:18','Minh Anh','VIEW','MedicalRecord #451','10.10.2.14'],['09:38:04','TS.BS Nguyễn Văn An','UPDATE','MedicalRecord #451','10.10.2.21'],['09:32:51','Trần Quốc Bảo','DISPENSE','Prescription #332','10.10.2.35'],['09:26:10','System Admin','Cập nhật vai trò','User #112','10.10.1.5']]
  return <><Header action={<Button variant="secondary"><Download className="size-4" /> Xuất nhật ký</Button>} /><Card className="overflow-hidden"><div className="grid gap-3 border-b border-slate-100 p-4 sm:grid-cols-[1fr_auto_auto]"><SearchBox placeholder="Tìm người dùng, đối tượng..." /><SelectBox>Hành động: Tất cả</SelectBox><SelectBox>Hôm nay</SelectBox></div><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Thời gian</th><th>Người thực hiện</th><th>Hành động</th><th>Đối tượng</th><th>Địa chỉ IP</th><th /></tr></thead><tbody>{logs.map(r => <tr key={r[0]}><td><strong>01/10/2026</strong><span className="block text-xs text-slate-400">{r[0]}</span></td><td>{r[1]}</td><td><Badge tone={r[2] === 'VIEW' ? 'info' : r[2] === 'UPDATE' ? 'warning' : 'success'}>{r[2]}</Badge></td><td className="font-mono text-xs">{r[3]}</td><td className="font-mono text-xs text-slate-500">{r[4]}</td><td><button className="text-xs font-bold text-teal-700">Chi tiết</button></td></tr>)}</tbody></table></div></Card></>
}

function ReceiptPage() {
  return <><Header /><div className="grid gap-6 xl:grid-cols-[1fr_320px]"><Card className="p-6"><h2 className="font-display text-lg font-bold">Thông tin phiếu nhập</h2><div className="mt-5 grid gap-5 sm:grid-cols-3"><Field label="Nhà cung cấp *" value="Dược Hậu Giang" /><Field label="Số chứng từ *" value="DHG-011026-14" /><Field label="Ngày nhập *" type="date" value="2026-10-01" /></div><div className="my-6 border-t border-slate-100" /><div className="flex items-center justify-between"><h3 className="font-display font-bold">Chi tiết lô thuốc</h3><Button variant="secondary"><Plus className="size-4" /> Thêm dòng</Button></div><div className="mt-4 overflow-x-auto"><table className="data-table border border-slate-100"><thead><tr><th>Thuốc</th><th>Số lô</th><th>Hạn dùng</th><th>Số lượng</th><th>Giá nhập</th><th /></tr></thead><tbody>{[['Paracetamol 500mg','PAR-1026','30/10/2028','1.000','420đ'],['Aspirin 81mg','ASP-1026','15/09/2028','500','780đ']].map(r => <tr key={r[0]}>{r.map(c => <td key={c}>{c}</td>)}<td><Trash2 className="size-4 text-slate-400" /></td></tr>)}</tbody></table></div></Card><Card className="self-start p-5"><h3 className="font-display font-bold">Tổng phiếu nhập</h3><div className="mt-5 space-y-3 text-sm"><p className="flex justify-between"><span className="text-slate-400">Số mặt hàng</span><b>2</b></p><p className="flex justify-between"><span className="text-slate-400">Tổng số lượng</span><b>1.500</b></p><p className="flex justify-between border-t border-slate-100 pt-3"><span className="text-slate-500">Tổng tiền</span><b className="font-display text-xl text-teal-700">810.000đ</b></p></div><Button className="mt-5 w-full"><CheckCircle2 className="size-4" /> Hoàn tất nhập kho</Button></Card></div></>
}

function PatientListPage({ type }: { type: 'appointments' | 'records' | 'invoices' }) {
  const config = type === 'appointments' ? { rows: [['A2026-0451','01/10/2026 · 09:00','TS.BS Nguyễn Văn An','Tim mạch','Đã xác nhận'],['A2026-0382','12/03/2026 · 14:30','BS. Lê Hoàng Nam','Nội tổng quát','Hoàn tất']], columns: ['Mã lịch hẹn','Thời gian','Bác sĩ','Chuyên khoa','Trạng thái'], action: 'Đặt lịch mới' } : type === 'records' ? { rows: [['BA2026-0451','01/10/2026','Đau thắt ngực ổn định (I20.8)','TS.BS Nguyễn Văn An','Đã chốt'],['BA2026-0164','12/03/2026','Viêm họng cấp (J02.9)','BS. Lê Hoàng Nam','Đã chốt']], columns: ['Mã bệnh án','Ngày khám','Chẩn đoán','Bác sĩ','Trạng thái'], action: 'Tải hồ sơ' } : { rows: [['HD2026-000871','01/10/2026','560.000đ','200.000đ','360.000đ'],['HD2026-000512','12/03/2026','250.000đ','250.000đ','0đ']], columns: ['Số hóa đơn','Ngày','Tổng tiền','Đã trả','Còn lại'], action: 'Tải hóa đơn' }
  return <><Header action={<Button>{type === 'appointments' ? <CalendarDays className="size-4" /> : <Download className="size-4" />}{config.action}</Button>} /><Card className="overflow-hidden"><div className="flex gap-3 border-b border-slate-100 p-4"><SearchBox placeholder="Tìm trong danh sách..." /><SelectBox>12 tháng gần nhất</SelectBox></div><div className="overflow-x-auto"><table className="data-table"><thead><tr>{config.columns.map(c=><th key={c}>{c}</th>)}<th /></tr></thead><tbody>{config.rows.map(r=><tr key={r[0]}>{r.map((c,i)=><td key={c} className={i === 0 ? 'font-bold text-teal-700' : ''}>{i === r.length - 1 && type !== 'invoices' ? <Badge tone="success">{c}</Badge> : c}</td>)}<td><Button variant="ghost">Xem chi tiết <ChevronRight className="size-4" /></Button></td></tr>)}</tbody></table></div></Card></>
}

function GenericFormPage() {
  return <><Header /><Card className="p-7"><div className="grid gap-5 sm:grid-cols-2"><Field label="Họ và tên" placeholder="Nhập họ tên..." /><Field label="Số điện thoại" placeholder="Nhập số điện thoại..." /><Field label="Ngày sinh" type="date" /><Field label="Địa chỉ" placeholder="Nhập địa chỉ..." /><Field label="Ghi chú" type="textarea" className="sm:col-span-2" /></div><div className="mt-6 flex justify-end gap-3"><Button variant="secondary">Hủy</Button><Button>Lưu thông tin</Button></div></Card></>
}

function WorkspaceContent() {
  const { pathname } = useLocation()
  if (pathname === '/reception') return <ReceptionPage />
  if (pathname === '/reception/patients') return <PatientsPage />
  if (pathname === '/reception/booking') return <StaffBookingPage />
  if (pathname === '/reception/queue') return <QueuePage />
  if (pathname.startsWith('/reception/cashier')) return <CashierPage />
  if (pathname === '/booking') return <BookingPage />
  if (pathname === '/my-appointments') return <PatientListPage type="appointments" />
  if (pathname === '/my-records') return <PatientListPage type="records" />
  if (pathname === '/my-invoices') return <PatientListPage type="invoices" />
  if (pathname === '/doctor/queue') return <QueuePage doctor />
  if (/^\/doctor\/exam\/[^/]+\/services/.test(pathname)) return <ClinicalServicesPage />
  if (/^\/doctor\/exam\/[^/]+\/prescription/.test(pathname)) return <PrescriptionPage />
  if (/^\/doctor\/exam\//.test(pathname)) return <ExamPage />
  if (pathname === '/technician/orders' || pathname === '/technician/results') return <ClinicalServicesPage technician />
  if (pathname === '/pharmacy/inventory') return <InventoryPage />
  if (pathname.startsWith('/pharmacy/dispense')) return <PrescriptionPage dispensing />
  if (pathname === '/pharmacy/receipt') return <ReceiptPage />
  if (pathname === '/admin/reports') return <AdminDashboard />
  if (pathname === '/admin/audit-logs') return <AuditPage />
  if (pathname in managementData) return <ManagementPage path={pathname as keyof typeof managementData} />
  return <GenericFormPage />
}

export default function WorkspacePages() {
  return <AppShell><WorkspaceContent /></AppShell>
}
