import type { Invoice } from '../types/billing'
import { formatPaymentMoney } from '../schemas/payment-schema'
import { hasSimulatedPayments, invoicePrintStatus, printDateTime, printPaymentMethod } from '../schemas/invoice-print-schema'
import logo from '../../../assets/images/FoMed_Logo.png'

export default function InvoicePrintSheet({ invoice, loadedAt }: { invoice: Invoice; loadedAt: string }) {
  const simulated = hasSimulatedPayments(invoice)
  return <article className="invoice-print-sheet" aria-label={`Bản in hóa đơn ${invoice.invoiceNo}`}>
    <header className="invoice-print-header"><div className="invoice-print-brand"><img src={logo} width="44" height="44" alt="" /><div><strong>FoMed</strong><p>Chi phí khám và thanh toán</p></div></div><div className="invoice-print-document"><h1>HÓA ĐƠN DỊCH VỤ</h1><p>Mã hóa đơn: <strong>{invoice.invoiceNo}</strong></p><p>Ngày lập: {printDateTime(invoice.createdAt!)}</p></div></header>
    <div className="invoice-print-patient"><p><span>Bệnh nhân</span><strong>{invoice.patientName}</strong></p><p><span>Mã bệnh nhân</span><strong>{invoice.patientCode}</strong></p><p><span>Trạng thái</span><strong>{invoicePrintStatus(invoice)}</strong></p></div>
    {invoice.status === 2 && <p className="invoice-print-warning">HÓA ĐƠN ĐÃ HỦY — Không sử dụng để thu tiền.</p>}
    {invoice.status !== 2 && invoice.status !== 1 && <p className="invoice-print-notice">Hóa đơn chưa được thanh toán đầy đủ. Phiếu này không xác nhận đã thu đủ tiền.</p>}
    {simulated && <p className="invoice-print-warning">CÓ GIAO DỊCH MÔ PHỎNG — Khoản thu thử nghiệm không phải tiền chuyển thực tế.</p>}
    <table className="invoice-print-lines"><caption>Chi tiết chi phí</caption><colgroup><col className="invoice-print-number" /><col /><col className="invoice-print-quantity" /><col className="invoice-print-price" /><col className="invoice-print-price" /></colgroup><thead><tr><th scope="col">STT</th><th scope="col">Nội dung</th><th scope="col" className="number">SL</th><th scope="col" className="number">Đơn giá</th><th scope="col" className="number">Thành tiền</th></tr></thead><tbody>
      {invoice.consultationFee > 0 && <tr><td>1</td><td>Phí khám</td><td className="number">1</td><td className="number">{formatPaymentMoney(invoice.consultationFee)}</td><td className="number">{formatPaymentMoney(invoice.consultationFee)}</td></tr>}
      {invoice.items.map((item, index) => <tr key={index}><td>{index + (invoice.consultationFee > 0 ? 2 : 1)}</td><td className="description">{item.description || 'Khoản mục khác'}</td><td className="number">{item.quantity.toLocaleString('vi-VN')}</td><td className="number">{formatPaymentMoney(item.unitPrice)}</td><td className="number">{formatPaymentMoney(item.amount)}</td></tr>)}
    </tbody></table>
    <section className="invoice-print-totals" aria-label="Tổng kết hóa đơn"><dl><div><dt>Tổng chi phí</dt><dd>{formatPaymentMoney(invoice.totalAmount)}</dd></div><div><dt>Đã thu vào hóa đơn</dt><dd>{formatPaymentMoney(invoice.paidAmount)}</dd></div>{invoice.status !== 2 && <div className="invoice-print-total"><dt>Còn phải thu</dt><dd>{formatPaymentMoney(Number((invoice.totalAmount - invoice.paidAmount).toFixed(2)))}</dd></div>}</dl></section>
    <section className="invoice-print-payments" aria-label="Khoản thu đã ghi nhận"><h2>Khoản thu đã ghi nhận</h2>{invoice.payments.length === 0 ? <p>Chưa có khoản thu được ghi nhận.</p> : <table><caption className="invoice-print-visually-hidden">Lịch sử các khoản thu đã lưu</caption><thead><tr><th scope="col">Thời gian / hình thức</th><th scope="col">Thông tin ghi nhận</th><th scope="col" className="number">Đã thu</th></tr></thead><tbody>{[...invoice.payments].sort((a, b) => a.id - b.id).map(payment => <tr key={payment.id}><td>{printDateTime(payment.paidAt)}<br />{printPaymentMethod(payment.method)}{payment.providerEnvironment === 'Test' && <strong className="invoice-print-simulation-label">Mô phỏng</strong>}</td><td className="description">{payment.provider === 'SePay' ? <>SePay xác nhận{payment.providerTransactionId != null && <> · Giao dịch #{payment.providerTransactionId}</>}</> : <>Người thu: {payment.receivedByName || 'Chưa ghi nhận'}</>}{payment.method === 0 && <div className="invoice-print-cash">{payment.cashReceived != null && payment.changeAmount != null ? <><p>Khách đưa: {formatPaymentMoney(payment.cashReceived)}</p><p>Tiền thừa: {formatPaymentMoney(payment.changeAmount)}</p></> : <p>Chưa ghi nhận tiền khách đưa / tiền thừa.</p>}</div>}</td><td className="number">{formatPaymentMoney(payment.amount)}</td></tr>)}</tbody></table>}</section>
    <footer className="invoice-print-footer"><p>Thông tin được tải lúc {printDateTime(loadedAt)} (giờ Việt Nam).</p><p>Phiếu thông tin chi phí và thanh toán của FoMed. Tiền khách đưa và tiền thừa không làm tăng khoản thu.</p><p>Vui lòng kiểm tra mã hóa đơn và các khoản thu trước khi đối chiếu.</p></footer>
  </article>
}
